"""Reusable deterministic strategy components — not validated strategies."""
from __future__ import annotations

from typing import Any

COMPONENT_IDS = (
    "TREND_CONTINUATION",
    "STRUCTURAL_RETEST",
    "BREAKOUT",
    "FAILED_BREAKOUT",
    "MOMENTUM_ACCELERATION",
    "VOLATILITY_EXPANSION",
    "VWAP_MEAN_REVERSION",
    "STRUCTURAL_MEAN_REVERSION",
    "RELATIVE_STRENGTH",
    "CROSS_SECTIONAL_MOMENTUM",
    "LIQUIDITY_SWEEP_REVERSAL",
    "FUNDING_OI_CONTINUATION",
    "FUNDING_OI_CONTRARIAN",
    "REGIME_TRANSITION_VETO",
    "MARK_INDEX_BASIS_ANOMALY",
    "VOLUME_EXPANSION_EVENT",
)


def _comp(
    *,
    component_id: str,
    required_data: list[str],
    valid_regimes: list[str],
    invalid_regimes: list[str],
    entry_event: str,
    cost_dependency: str,
    liquidity_dependency: str,
    known_failure_modes: list[str],
    strategy_family: str,
) -> dict[str, Any]:
    return {
        "component_id": component_id,
        "strategy_family": strategy_family,
        "required_data": required_data,
        "valid_regimes": valid_regimes,
        "invalid_regimes": invalid_regimes,
        "entry_event": entry_event,
        "cost_dependency": cost_dependency,
        "liquidity_dependency": liquidity_dependency,
        "known_failure_modes": known_failure_modes,
        "validated_strategy": False,
    }


def component_registry() -> dict[str, Any]:
    comps = [
        _comp(
            component_id="TREND_CONTINUATION",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["TRENDING_UP", "TRENDING_DOWN"],
            invalid_regimes=["RANGE", "CHAOS"],
            entry_event="pullback_then_resume",
            cost_dependency="spread_and_taker",
            liquidity_dependency="turnover_floor",
            known_failure_modes=["late_entry", "regime_flip"],
            strategy_family="TREND",
        ),
        _comp(
            component_id="STRUCTURAL_RETEST",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["TRENDING_UP", "TRENDING_DOWN", "RANGE"],
            invalid_regimes=["CHAOS"],
            entry_event="retest_of_broken_level",
            cost_dependency="spread_and_taker",
            liquidity_dependency="spread_cap",
            known_failure_modes=["false_structure", "stop_too_tight"],
            strategy_family="STRUCTURE",
        ),
        _comp(
            component_id="BREAKOUT",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["RANGE", "VOL_EXPAND"],
            invalid_regimes=["CHAOS"],
            entry_event="range_high_low_break",
            cost_dependency="slippage_sensitive",
            liquidity_dependency="volume_expansion",
            known_failure_modes=["fakeout", "cost_dominated"],
            strategy_family="BREAKOUT",
        ),
        _comp(
            component_id="FAILED_BREAKOUT",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["RANGE", "VOL_EXPAND"],
            invalid_regimes=["STRONG_TREND"],
            entry_event="break_then_reclaim",
            cost_dependency="spread_and_taker",
            liquidity_dependency="spread_cap",
            known_failure_modes=["continuation_after_fail"],
            strategy_family="BREAKOUT",
        ),
        _comp(
            component_id="MOMENTUM_ACCELERATION",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["TRENDING_UP", "TRENDING_DOWN", "VOL_EXPAND"],
            invalid_regimes=["RANGE"],
            entry_event="atr_acceleration",
            cost_dependency="slippage_sensitive",
            liquidity_dependency="turnover_floor",
            known_failure_modes=["exhaustion"],
            strategy_family="MOMENTUM",
        ),
        _comp(
            component_id="VOLATILITY_EXPANSION",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["VOL_EXPAND"],
            invalid_regimes=["LOW_VOL"],
            entry_event="atr_percentile_break",
            cost_dependency="wide_spread_risk",
            liquidity_dependency="volume_expansion",
            known_failure_modes=["whipsaw"],
            strategy_family="VOLATILITY",
        ),
        _comp(
            component_id="VWAP_MEAN_REVERSION",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["RANGE", "LOW_VOL"],
            invalid_regimes=["STRONG_TREND"],
            entry_event="deviation_from_vwap",
            cost_dependency="cost_sensitive_mean_reversion",
            liquidity_dependency="spread_cap",
            known_failure_modes=["trend_day"],
            strategy_family="MEAN_REVERSION",
        ),
        _comp(
            component_id="STRUCTURAL_MEAN_REVERSION",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["RANGE"],
            invalid_regimes=["STRONG_TREND"],
            entry_event="touch_range_extreme",
            cost_dependency="cost_sensitive_mean_reversion",
            liquidity_dependency="spread_cap",
            known_failure_modes=["range_break"],
            strategy_family="MEAN_REVERSION",
        ),
        _comp(
            component_id="RELATIVE_STRENGTH",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["TRENDING_UP", "TRENDING_DOWN"],
            invalid_regimes=["CHAOS"],
            entry_event="vs_btc_strength",
            cost_dependency="spread_and_taker",
            liquidity_dependency="turnover_floor",
            known_failure_modes=["beta_collapse"],
            strategy_family="CROSS_SECTIONAL",
        ),
        _comp(
            component_id="CROSS_SECTIONAL_MOMENTUM",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["TRENDING_UP", "TRENDING_DOWN"],
            invalid_regimes=["CHAOS"],
            entry_event="rank_momentum_bucket",
            cost_dependency="turnover_cost",
            liquidity_dependency="turnover_floor",
            known_failure_modes=["crowding"],
            strategy_family="CROSS_SECTIONAL",
        ),
        _comp(
            component_id="LIQUIDITY_SWEEP_REVERSAL",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["RANGE", "VOL_EXPAND"],
            invalid_regimes=["STRONG_TREND"],
            entry_event="sweep_then_reclaim",
            cost_dependency="slippage_sensitive",
            liquidity_dependency="depth_sensitive",
            known_failure_modes=["true_break"],
            strategy_family="REVERSAL",
        ),
        _comp(
            component_id="FUNDING_OI_CONTINUATION",
            required_data=["DERIVATIVES_HISTORY_ELIGIBLE"],
            valid_regimes=["TRENDING_UP", "TRENDING_DOWN"],
            invalid_regimes=["RANGE"],
            entry_event="funding_oi_aligned",
            cost_dependency="funding_aware",
            liquidity_dependency="oi_floor",
            known_failure_modes=["crowded_unwind"],
            strategy_family="DERIVATIVES",
        ),
        _comp(
            component_id="FUNDING_OI_CONTRARIAN",
            required_data=["DERIVATIVES_HISTORY_ELIGIBLE"],
            valid_regimes=["RANGE", "VOL_EXPAND"],
            invalid_regimes=["STRONG_TREND"],
            entry_event="extreme_funding_fade",
            cost_dependency="funding_aware",
            liquidity_dependency="oi_floor",
            known_failure_modes=["squeeze_continuation"],
            strategy_family="DERIVATIVES",
        ),
        _comp(
            component_id="REGIME_TRANSITION_VETO",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["ANY"],
            invalid_regimes=[],
            entry_event="veto_on_regime_shift",
            cost_dependency="none",
            liquidity_dependency="none",
            known_failure_modes=["lagged_regime"],
            strategy_family="REGIME_CONTROL",
        ),
        _comp(
            component_id="MARK_INDEX_BASIS_ANOMALY",
            required_data=["DERIVATIVES_HISTORY_ELIGIBLE", "PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["ANY"],
            invalid_regimes=[],
            entry_event="basis_dislocation",
            cost_dependency="basis_cost",
            liquidity_dependency="oi_floor",
            known_failure_modes=["persistent_basis"],
            strategy_family="DERIVATIVES",
        ),
        _comp(
            component_id="VOLUME_EXPANSION_EVENT",
            required_data=["PRICE_HISTORY_ELIGIBLE"],
            valid_regimes=["VOL_EXPAND", "TRENDING_UP", "TRENDING_DOWN"],
            invalid_regimes=["LOW_VOL"],
            entry_event="volume_zscore_spike",
            cost_dependency="slippage_sensitive",
            liquidity_dependency="volume_expansion",
            known_failure_modes=["one_bar_spike"],
            strategy_family="VOLUME",
        ),
    ]
    return {
        "schema": "strategy_component_registry_v1",
        "validated_strategies": False,
        "component_count": len(comps),
        "components": comps,
    }
