"""NEXUS General Multi-Strategy Research Engine V1.

Development research only — no fleets, no formal WF, no OOS, no Demo.
"""
from __future__ import annotations

STRATEGY_SPEC_SCHEMA_VERSION = "NEXUS_STRATEGY_SPEC_V1"
EVIDENCE_SCHEMA_VERSION = "NEXUS_DECISION_OUTCOME_EVIDENCE_V2"
ENGINE_STAGE = "GENERAL_MULTI_STRATEGY_RESEARCH_ENGINE_V1"

from backend.nexus_execution.cost_model import (
    DEFAULT_TAKER_FEE,
    TAKER_FEE as _CANONICAL_TAKER_FEE,
)

MARGIN_MODE = "ISOLATED"
LEVERAGE = 25
POSITION_MARGIN_USDT = 20.0
MAX_LOSS_RISK_PER_TRADE = 3.0
# Canonical fee authority: backend.nexus_execution.cost_model
TAKER_FEE_RATE = float(DEFAULT_TAKER_FEE)
assert TAKER_FEE_RATE == _CANONICAL_TAKER_FEE
DEFAULT_ROUND_TRIP_RATE = TAKER_FEE_RATE * 2.0

MAX_DEVELOPMENT_HYPOTHESES = 12
MIN_STRATEGY_FAMILIES = 4

DISCOVERY_STATUSES = frozenset(
    {
        "DISCOVERY_PROMISING",
        "DISCOVERY_NO_GROSS_EDGE",
        "DISCOVERY_COST_DOMINATED",
        "DISCOVERY_FOLD_CONCENTRATED",
        "DISCOVERY_SYMBOL_CONCENTRATED",
        "DISCOVERY_REGIME_CONCENTRATED",
        "DISCOVERY_INSUFFICIENT_SAMPLE",
        "DISCOVERY_DATA_INVALID",
        "DISCOVERY_IMPLEMENTATION_INVALID",
    }
)

DETERMINISTIC_PROCESS = frozenset(
    {
        "PROCESS_COMPLIANT",
        "PROCESS_NONCOMPLIANT",
        "PROCESS_EVIDENCE_INSUFFICIENT",
    }
)

INTEGRATION_LESSON_STATUSES = frozenset(
    {
        "INTEGRATION_PROOF_ONLY",
        "PROPOSED_INSUFFICIENT_SOURCE_EVIDENCE",
    }
)

MISSING = "MISSING"
UNKNOWN = "UNKNOWN"
UNAVAILABLE = "UNAVAILABLE"
