/**
 * Market Brief — a product-like brief panel. The brief is generated by the
 * BACKEND (deterministic, rule-based) from real public market state. It is
 * explicitly labelled as deterministic (NOT AI-generated) and never exposes
 * private/Founder AI. Source: /api/corporate/v1/brief.
 */
import { useEffect, useState } from "react";
import { getBrief } from "../../api/client";
import { fmtTime } from "../../lib/format";
import type { MarketBrief as Brief } from "../../types";

export function MarketBrief() {
  const [b, setB] = useState<Brief | null | undefined>(undefined);
  useEffect(() => {
    let on = true;
    const load = () => getBrief().then((r) => on && setB(r)).catch(() => on && setB(null));
    load();
    const t = window.setInterval(() => { if (!document.hidden) load(); }, 30000);
    return () => { on = false; window.clearInterval(t); };
  }, []);

  if (b === undefined) return <div className="corp-fs-brief"><div className="corp-fs-brief-main corp-fs-loading" role="status">產生市場簡報…</div><div className="corp-fs-brief-side" /></div>;
  if (!b || b.availability !== "READY") {
    return <div className="corp-fs-brief"><div className="corp-fs-brief-main corp-fs-unavail">市場簡報暫不可用</div><div className="corp-fs-brief-side" /></div>;
  }

  return (
    <div className="corp-fs-brief" data-testid="market-brief">
      <div className="corp-fs-brief-main">
        <span className="corp-fs-brief-tag">Deterministic Brief · 規則生成</span>
        <h4>目前市場</h4>
        <div className="corp-fs-brief-body">
          {(b.summary ?? []).map((line, i) => <p key={i} style={{ margin: "0 0 0.4rem" }}>{line}</p>)}
        </div>
        <div className="corp-fs-brief-meta">
          資料 · {(b.data_used ?? []).join(" / ")} · 來源 {b.source} · 更新 {fmtTime(b.updated_at)}
          <br />由後端規則生成，非 AI 生成。不含私有交易情報。
        </div>
      </div>
      <div className="corp-fs-brief-side">
        <h4>需要關注 · Watch</h4>
        <ul className="corp-fs-brief-list">{(b.watch ?? []).map((w, i) => <li key={i}>{w}</li>)}</ul>
        <h4 style={{ marginTop: "1.1rem" }}>風險 · Risk</h4>
        <ul className="corp-fs-brief-list">{(b.risk ?? []).map((r, i) => <li key={i}>{r}</li>)}</ul>
      </div>
    </div>
  );
}
