/**
 * Market Brief panel. The brief is generated by the BACKEND (deterministic,
 * rule-based, localized) and delivered via the realtime context (SSE brief_update
 * with polling fallback). Explicitly labelled NOT AI-generated; never exposes
 * private/Founder AI.
 */
import { useBrief } from "../../context/MarketContext";
import { useLocale } from "../../i18n";
import { fmtTime } from "../../lib/format";

export function MarketBrief() {
  const b = useBrief();
  const { t } = useLocale();

  if (b === null) return <div className="corp-fs-brief"><div className="corp-fs-brief-main corp-fs-loading" role="status">{t("st_loading")}</div><div className="corp-fs-brief-side" /></div>;
  if (b.availability !== "READY") {
    return <div className="corp-fs-brief"><div className="corp-fs-brief-main corp-fs-unavail">{t("st_unavailable")}</div><div className="corp-fs-brief-side" /></div>;
  }
  return (
    <div className="corp-fs-brief" data-testid="market-brief">
      <div className="corp-fs-brief-main">
        <span className="corp-fs-brief-tag">Deterministic Brief</span>
        <h4>{t("brief_now")}</h4>
        <div className="corp-fs-brief-body">
          {(b.summary ?? []).map((line, i) => <p key={i} style={{ margin: "0 0 0.4rem" }}>{line}</p>)}
        </div>
        <div className="corp-fs-brief-meta">
          {(b.data_used ?? []).join(" / ")} · {b.source} · {fmtTime(b.updated_at)}
          <br />{t("brief_note")}
        </div>
      </div>
      <div className="corp-fs-brief-side">
        <h4>{t("brief_watch")}</h4>
        <ul className="corp-fs-brief-list">{(b.watch ?? []).map((w, i) => <li key={i}>{w}</li>)}</ul>
        <h4 style={{ marginTop: "1.1rem" }}>{t("brief_risk")}</h4>
        <ul className="corp-fs-brief-list">{(b.risk ?? []).map((r, i) => <li key={i}>{r}</li>)}</ul>
      </div>
    </div>
  );
}
