/**
 * News provider foundation (Product 7.2).
 * Empty / unavailable honest states. Never invents headlines.
 * lastAttempted tracked. Distinguishes: pending / unavailable / empty / error.
 */

import {
  unavailableMetric,
  isStale,
  initialProviderState,
  type ParityMetric,
  type ProviderState,
} from "../parityContracts";

export type NewsItem = {
  id: string;
  title: string;
  source?: string;
  publishedAt?: number | null;
  url?: string | null;
  /** Relevance tag from provider — never generated by NEXUS. */
  tags?: string[];
};

export type NewsFeedValue = {
  items: NewsItem[];
  /** Total available from provider, before limit. */
  totalAvailable?: number | null;
  /** Empty-vs-unavailable distinction: empty means provider replied with 0 items. */
  feedState: "populated" | "empty" | "unavailable";
};

export type NewsProvider = {
  providerId: string;
  getState(): ProviderState;
  isAvailable(): Promise<boolean>;
  getHeadlines(limit?: number): Promise<ParityMetric<NewsFeedValue>>;
};

export class NewsProviderPending implements NewsProvider {
  providerId = "NEWS_PROVIDER_PENDING";

  private state: ProviderState = initialProviderState();

  getState(): ProviderState {
    return { ...this.state };
  }

  async isAvailable(): Promise<boolean> {
    this.state = {
      ...this.state,
      lastAttempted: Date.now(),
      availability: "unavailable",
    };
    return false;
  }

  async getHeadlines(_limit = 10): Promise<ParityMetric<NewsFeedValue>> {
    const now = Date.now();
    this.state = {
      ...this.state,
      lastAttempted: now,
      consecutiveFailures: this.state.consecutiveFailures + 1,
      availability: "unavailable",
      lastError: "provider not configured",
    };

    return unavailableMetric<NewsFeedValue>(
      "News Headlines",
      this.providerId,
      [
        "PROVIDER_PENDING · 尚未接入新聞數據源",
        "不顯示假新聞標題",
        "接入後需明確區分 feedState: populated | empty | unavailable",
        "empty ≠ unavailable（provider 回覆 0 筆 vs provider 無回應）",
      ].join(" · "),
      this.state,
    );
  }
}

export const newsProvider: NewsProvider = new NewsProviderPending();

/**
 * Empty feed honest wrapper — for when provider replies but has 0 items.
 * Distinct from unavailable (provider didn't respond).
 */
export function makeEmptyNewsFeed(
  source: string,
  lastSuccessful: number,
): ParityMetric<NewsFeedValue> {
  const ageMin = Math.round((Date.now() - lastSuccessful) / 60_000);
  const stale = isStale(lastSuccessful);
  return {
    status: stale ? "stale" : "live",
    value: { items: [], feedState: "empty", totalAvailable: 0 },
    label: "News Headlines",
    freshness: stale
      ? `${ageMin} 分鐘前更新（已過期）`
      : new Date(lastSuccessful).toLocaleTimeString(),
    lastAttempted: new Date().toISOString(),
    lastSuccessful: new Date(lastSuccessful).toISOString(),
    sampleCount: 0,
    coverageNote: "提供者回覆空新聞列表（非無法連線）",
    error: null,
    source,
  };
}
