"""V18.2.17 Research AI Autonomy — constants and hard safety bounds."""
from __future__ import annotations

SCHEMA = "v18_2_17_research_ai_autonomy_v1"
PACKAGE = "backend.nexus_research_ai_autonomy"
DIRECTIVE = "FOUNDER_V18_2_17_RESEARCH_AI_AUTONOMY"
EXECUTION_PURPOSE_RESEARCH = "RESEARCH_AI_DEMO"
EXECUTION_PURPOSE_RESEARCH_REAL = "RESEARCH_AI_DEMO_REAL_EXCHANGE"
EXECUTION_PURPOSE_QUALIFIED = "QUALIFIED_SYSTEM_DEMO"
TRANSPORT_MODE_REAL = "BYBIT_DEMO_REAL_TRANSPORT"
TRANSPORT_MODE_SIM = "LOCAL_SIMULATION"

POLICY_RESEARCH_AI_DEMO = "RESEARCH_AI_DEMO"
POLICY_QUALIFIED_SYSTEM_DEMO = "QUALIFIED_SYSTEM_DEMO"

# Nine implemented real strategy families (V18.2.16 registry — do not invent).
IMPLEMENTED_STRATEGY_FAMILIES: tuple[str, ...] = (
    "BREAKOUT",
    "CROSS_SECTIONAL",
    "DERIVATIVES",
    "MEAN_REVERSION",
    "MOMENTUM",
    "REVERSAL",
    "STRUCTURE",
    "TREND",
    "VOLATILITY",
)

REGIME_TYPES: tuple[str, ...] = (
    "TREND_UP",
    "TREND_DOWN",
    "RANGE",
    "BREAKOUT",
    "HIGH_VOLATILITY",
    "LOW_VOLATILITY",
    "CROWDING",
    "LIQUIDITY_STRESS",
    "UNCERTAIN",
)

PREPARED_DECISION_STATES: tuple[str, ...] = (
    "PREPARING",
    "READY",
    "TRIGGERED",
    "INVALIDATED",
    "EXPIRED",
    "EXECUTED",
    "REJECTED",
)

PROCESS_CLASSES: tuple[str, ...] = (
    "GOOD_PROCESS_WIN",
    "GOOD_PROCESS_LOSS",
    "BAD_PROCESS_WIN",
    "BAD_PROCESS_LOSS",
)

ERROR_ONTOLOGY: tuple[str, ...] = (
    "DATA_ERROR",
    "REGIME_ERROR",
    "STRATEGY_ERROR",
    "AI_REASONING_ERROR",
    "EXECUTION_ERROR",
    "RISK_ERROR",
    "TIMING_ERROR",
    "UNAVOIDABLE_MARKET_OUTCOME",
)

# Exploration budget (cap, not target).
DEFAULT_MAX_NEW_ENTRIES_24H = 6
DEFAULT_MAX_CONCURRENT = 1
DEFAULT_LEVERAGE = 1
DEFAULT_MAX_HOLD_SEC = 3600
DEFAULT_PREPARED_TTL_SEC = 900
DEFAULT_RESEARCH_SHORTLIST_N = 8

# V18.2.24/25 — purpose-aware hold / sizing bounds (RESEARCH_PNL_TRADE)
EXECUTION_CANARY_MAX_HOLD_SEC = 45
# RESEARCH_PNL — no arbitrary mandatory min hold; thesis horizon from family table
RESEARCH_PNL_MIN_HOLD_SEC = 0
RESEARCH_PNL_DEFAULT_MAX_HOLD_SEC = 3600
RESEARCH_PNL_PREFERRED_NOTIONAL_MIN = 250.0
RESEARCH_PNL_PREFERRED_NOTIONAL_MAX = 500.0
RESEARCH_PNL_MAX_LOSS_EQUITY_PCT = 0.10
RESEARCH_PNL_PREFERRED_EXPECTED_NET_TP_USDT = 1.0

# Safety invariants
DEMO_ONLY = True
MEMBER_EXECUTION = 0
MAINNET_WRITES = 0
REAL_MONEY = False
ACTIVE_LESSONS_FROM_LIVE_DEMO_DEFAULT = 0

BYBIT_DEMO_HOST = "api-demo.bybit.com"
DEMO_REST_BASE_URL = f"https://{BYBIT_DEMO_HOST}"
