"""NEXUS Edge Discovery Diagnostics V2 — separate raw event edge from strategy PnL."""
from __future__ import annotations

PACKAGE = "NEXUS_EDGE_DISCOVERY_DIAGNOSTICS_V2"
EVENT_STUDY_ENGINE = "NEXUS_EVENT_STUDY_ENGINE_V1"
BLIND_REFLECTION = "BLIND_REFLECTION_V2_2"
INTERVAL_REGISTRY = "NEXUS_EDGE_DISCOVERY_DEVELOPMENT_INTERVAL_REGISTRY_V1"
RANDOM_SEED = 20260803
BOOTSTRAP_BLOCK_BARS = 32
BOOTSTRAP_REPLICATES = 200
FORWARD_HORIZONS = (1, 2, 4, 8, 16, 32)

DIAGNOSTIC_STATUSES = frozenset(
    {
        "RAW_SIGNAL_NO_EDGE",
        "RAW_EDGE_COST_DESTROYED",
        "RAW_EDGE_UNSTABLE",
        "RAW_EDGE_FOLD_CONCENTRATED",
        "RAW_EDGE_SYMBOL_CONCENTRATED",
        "RAW_EDGE_REGIME_CONCENTRATED",
        "RARE_EDGE_INSUFFICIENT_SUPPORT",
        "EXECUTION_GATE_STARVED",
        "RAW_EDGE_DIAGNOSTIC_PROMISING",
        "DATA_OR_METRIC_INVALID",
    }
)

H11_STATUSES = frozenset(
    {
        "H11_RAW_SIGNAL_NOT_CONFIRMED",
        "H11_RAW_SIGNAL_COST_DESTROYED",
        "H11_RARE_SIGNAL_INSUFFICIENT_SUPPORT",
        "H11_RAW_SIGNAL_CONCENTRATED",
        "H11_RAW_SIGNAL_DIAGNOSTIC_PROMISING",
    }
)

H01_STATUSES = frozenset(
    {
        "H01_RAW_SIGNAL_NO_EDGE",
        "H01_RAW_EDGE_TOO_SMALL_FOR_COST",
        "H01_RAW_EDGE_UNSTABLE",
        "H01_RAW_EDGE_DIAGNOSTIC_PROMISING",
    }
)
