/**
 * Corporate-surface i18n (decoupled from the shared member i18n so adding locales
 * never disturbs other surfaces). One ACTIVE locale at a time — no mixed-language
 * display. Narrative chrome is fully localized per locale; short technical labels
 * (REGIME / 24H / LIVE / FRESH …) stay English as intentional secondary labels.
 * Business CONTENT is localized by the backend CMS (?locale), not here.
 */
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export const LOCALES = ["zh-TW", "en-US", "ja-JP", "ko-KR"] as const;
export type Locale = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: Locale = "zh-TW";
export const LOCALE_KEY = "nexus.corp.locale";
export const LOCALE_NAMES: Record<Locale, string> = {
  "zh-TW": "繁體中文", "en-US": "English", "ja-JP": "日本語", "ko-KR": "한국어",
};

type Dict = Record<string, string>;

const zhTW: Dict = {
  nav_products: "產品", nav_personal: "個人版", nav_enterprise: "企業版", nav_about: "關於",
  cta_start: "開始使用", cta_view: "查看產品", login: "登入",
  hero_eyebrow: "即時市場情報",
  jobs_title: "你可以用 NEXUS 做三件事",
  jobs_watch: "看市場", jobs_watch_d: "即時價格、波動與市場狀態，一眼掌握。",
  jobs_find: "找重點", jobs_find_d: "自動標示現在最值得注意的資產。",
  jobs_risk: "控風險", jobs_risk_d: "市場狀態與風險，隨時清楚可判讀。",
  live_title: "即時產品", live_sub: "同一個介面，看懂整個市場。",
  live_overview: "市場概況", live_dynamics: "市場動態", live_brief: "今日簡報",
  choose_title: "哪一個適合你？",
  choose_personal: "個人版", choose_personal_for: "個人研究者 / 投資者",
  choose_enterprise: "企業版", choose_enterprise_for: "團隊 / 研究部門 / 公司",
  choose_personal_cta: "進入個人版", choose_enterprise_cta: "了解企業版",
  trust_title: "值得信任的市場情報", trust_sub: "所有數字都來自後端、可追溯來源；私有交易與網站完全隔離。",
  trust_more: "詳細技術",
  cta_title: "把市場資料，變成可以判讀的情報", cta_sub: "即時、可追溯、唯讀的市場情報層。", cta_button: "開始使用",
  st_loading: "載入中…", st_unavailable: "暫不可用", st_stable: "穩定",
  attn_high: "高度關注", attn_med: "留意", attn_watch: "中度關注",
  theme_label: "主題", theme_system: "跟隨系統", theme_light: "淺色", theme_dark: "深色",
  lang_label: "語言",
  av_available: "已上線", av_planned: "即將推出", av_contact: "聯絡我們",
  brief_now: "目前市場", brief_watch: "需要關注", brief_risk: "風險", brief_note: "由後端規則生成，非 AI 生成。",
  feed_empty: "目前無事件",
  rt_live: "即時", rt_reconnect: "重新連線中…", rt_polling: "輪詢模式", rt_source: "來源",
};

const enUS: Dict = {
  nav_products: "Products", nav_personal: "Personal", nav_enterprise: "Enterprise", nav_about: "About",
  cta_start: "Get started", cta_view: "View products", login: "Log in",
  hero_eyebrow: "Live market intelligence",
  jobs_title: "Three things you can do with NEXUS",
  jobs_watch: "Watch the market", jobs_watch_d: "Live price, volatility and market state at a glance.",
  jobs_find: "Find what matters", jobs_find_d: "The assets that most need attention, surfaced for you.",
  jobs_risk: "Control risk", jobs_risk_d: "Market state and risk, always clear and readable.",
  live_title: "Live product", live_sub: "One interface — understand the whole market.",
  live_overview: "Overview", live_dynamics: "Activity", live_brief: "Today's brief",
  choose_title: "Which one is right for you?",
  choose_personal: "Personal", choose_personal_for: "Individual researchers / investors",
  choose_enterprise: "Enterprise", choose_enterprise_for: "Teams / research desks / companies",
  choose_personal_cta: "Enter Personal", choose_enterprise_cta: "Explore Enterprise",
  trust_title: "Market intelligence you can trust", trust_sub: "Every number is backend-sourced and traceable; private trading is fully isolated.",
  trust_more: "Technical details",
  cta_title: "Turn market data into intelligence you can read", cta_sub: "A real-time, traceable, read-only market intelligence layer.", cta_button: "Get started",
  st_loading: "Loading…", st_unavailable: "Unavailable", st_stable: "Stable",
  attn_high: "High attention", attn_med: "Watch", attn_watch: "Moderate",
  theme_label: "Theme", theme_system: "System", theme_light: "Light", theme_dark: "Dark",
  lang_label: "Language",
  av_available: "Available", av_planned: "Coming soon", av_contact: "Contact us",
  brief_now: "Market now", brief_watch: "Watch", brief_risk: "Risk", brief_note: "Generated by backend rules — not AI.",
  feed_empty: "No events yet",
  rt_live: "Live", rt_reconnect: "Reconnecting…", rt_polling: "Polling", rt_source: "Source",
};

const jaJP: Dict = {
  nav_products: "製品", nav_personal: "個人版", nav_enterprise: "企業版", nav_about: "会社概要",
  cta_start: "利用を開始", cta_view: "製品を見る", login: "ログイン",
  hero_eyebrow: "リアルタイム市場インテリジェンス",
  jobs_title: "NEXUS でできる 3 つのこと",
  jobs_watch: "市場を見る", jobs_watch_d: "価格・ボラティリティ・市場状態を一目で。",
  jobs_find: "要点を見つける", jobs_find_d: "いま注目すべき銘柄を自動で提示。",
  jobs_risk: "リスクを管理", jobs_risk_d: "市場状態とリスクを常に明確に。",
  live_title: "ライブ製品", live_sub: "ひとつの画面で市場全体を理解。",
  live_overview: "概況", live_dynamics: "動向", live_brief: "本日のブリーフ",
  choose_title: "どちらが最適ですか？",
  choose_personal: "個人版", choose_personal_for: "個人の研究者・投資家",
  choose_enterprise: "企業版", choose_enterprise_for: "チーム・調査部門・企業",
  choose_personal_cta: "個人版へ", choose_enterprise_cta: "企業版を見る",
  trust_title: "信頼できる市場インテリジェンス", trust_sub: "すべての数値はバックエンド由来で追跡可能。プライベート取引は完全に分離。",
  trust_more: "技術詳細",
  cta_title: "市場データを、読み解ける情報に", cta_sub: "リアルタイムで追跡可能な読み取り専用の市場情報レイヤー。", cta_button: "利用を開始",
  st_loading: "読み込み中…", st_unavailable: "利用不可", st_stable: "安定",
  attn_high: "高い注目", attn_med: "注意", attn_watch: "中程度",
  theme_label: "テーマ", theme_system: "システム", theme_light: "ライト", theme_dark: "ダーク",
  lang_label: "言語",
  av_available: "提供中", av_planned: "近日公開", av_contact: "お問い合わせ",
  brief_now: "現在の市場", brief_watch: "注目", brief_risk: "リスク", brief_note: "バックエンドのルールで生成（AIではありません）。",
  feed_empty: "イベントはまだありません",
  rt_live: "ライブ", rt_reconnect: "再接続中…", rt_polling: "ポーリング", rt_source: "ソース",
};

const koKR: Dict = {
  nav_products: "제품", nav_personal: "개인용", nav_enterprise: "기업용", nav_about: "소개",
  cta_start: "시작하기", cta_view: "제품 보기", login: "로그인",
  hero_eyebrow: "실시간 시장 인텔리전스",
  jobs_title: "NEXUS로 할 수 있는 세 가지",
  jobs_watch: "시장 보기", jobs_watch_d: "가격·변동성·시장 상태를 한눈에.",
  jobs_find: "핵심 찾기", jobs_find_d: "지금 주목할 자산을 자동으로 제시.",
  jobs_risk: "리스크 관리", jobs_risk_d: "시장 상태와 리스크를 항상 명확하게.",
  live_title: "라이브 제품", live_sub: "하나의 화면으로 시장 전체를 이해.",
  live_overview: "개요", live_dynamics: "동향", live_brief: "오늘의 브리핑",
  choose_title: "어떤 것이 맞나요?",
  choose_personal: "개인용", choose_personal_for: "개인 연구자 / 투자자",
  choose_enterprise: "기업용", choose_enterprise_for: "팀 / 리서치 부서 / 기업",
  choose_personal_cta: "개인용 시작", choose_enterprise_cta: "기업용 살펴보기",
  trust_title: "신뢰할 수 있는 시장 인텔리전스", trust_sub: "모든 수치는 백엔드 기반이며 추적 가능합니다. 프라이빗 트레이딩은 완전히 분리됩니다.",
  trust_more: "기술 상세",
  cta_title: "시장 데이터를 읽을 수 있는 인텔리전스로", cta_sub: "실시간으로 추적 가능한 읽기 전용 시장 정보 레이어.", cta_button: "시작하기",
  st_loading: "불러오는 중…", st_unavailable: "사용 불가", st_stable: "안정",
  attn_high: "높은 주의", attn_med: "주의", attn_watch: "보통",
  theme_label: "테마", theme_system: "시스템", theme_light: "라이트", theme_dark: "다크",
  lang_label: "언어",
  av_available: "제공 중", av_planned: "곧 출시", av_contact: "문의하기",
  brief_now: "현재 시장", brief_watch: "주목", brief_risk: "리스크", brief_note: "백엔드 규칙으로 생성 (AI 아님).",
  feed_empty: "아직 이벤트가 없습니다",
  rt_live: "실시간", rt_reconnect: "재연결 중…", rt_polling: "폴링", rt_source: "출처",
};

const DICTS: Record<Locale, Dict> = { "zh-TW": zhTW, "en-US": enUS, "ja-JP": jaJP, "ko-KR": koKR };

export function isLocale(v: unknown): v is Locale {
  return typeof v === "string" && (LOCALES as readonly string[]).includes(v);
}

type Ctx = { locale: Locale; setLocale: (l: Locale) => void; t: (key: string) => string };
const LocaleCtx = createContext<Ctx | null>(null);

function readStored(): Locale {
  try { const v = localStorage.getItem(LOCALE_KEY); if (isLocale(v)) return v; } catch { /* ignore */ }
  // fall back to the browser preference, else site default
  try {
    const nav = navigator.language;
    if (nav?.startsWith("ja")) return "ja-JP";
    if (nav?.startsWith("ko")) return "ko-KR";
    if (nav?.startsWith("en")) return "en-US";
  } catch { /* ignore */ }
  return DEFAULT_LOCALE;
}

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => readStored());
  useEffect(() => {
    document.documentElement.lang = locale;
    try { localStorage.setItem(LOCALE_KEY, locale); } catch { /* ignore */ }
  }, [locale]);
  const setLocale = useCallback((l: Locale) => setLocaleState(l), []);
  const t = useCallback((key: string) => DICTS[locale][key] ?? DICTS[DEFAULT_LOCALE][key] ?? key, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t }), [locale, setLocale, t]);
  return <LocaleCtx.Provider value={value}>{children}</LocaleCtx.Provider>;
}

export function useLocale(): Ctx {
  const ctx = useContext(LocaleCtx);
  if (!ctx) throw new Error("useLocale requires LocaleProvider");
  return ctx;
}
