"""DEMO_DATA fixtures for Member Web Intelligence Experience.

All fixtures are explicitly DEMO_DATA — never labeled LIVE.
"""
from __future__ import annotations

from typing import Any

from backend.nexus_public_member_intel.dto import (
    EvidenceItemDto,
    RegimeProbabilitiesDto,
    SimilarCaseSummaryDto,
)


FIXTURE_AS_OF = "2026-08-05T12:00:00Z"


def catalog() -> list[dict[str, Any]]:
    """Return member intel experience fixtures (DEMO_DATA mode)."""
    return [
        {
            "case_id": "mi_demo_wait_001",
            "symbol": "BTCUSDT",
            "decision_id": "pub_dec_mi_wait_001",
            "lifecycle_state": "AI_SUGGESTION",
            "uxa_lifecycle": "DECIDING",
            "posture": "WAIT",
            "mode": "DEMO_DATA",
            "data_freshness": "DEMO_DATA",
            "regime_label": "MIXED",
            "regime": RegimeProbabilitiesDto(
                strong_bull_probability=0.38,
                strong_bear_probability=0.27,
                volatility_expansion_probability=0.41,
                liquidity_stress_probability=0.22,
                long_crowding_probability=0.33,
                correlation_breakdown_probability=0.15,
                event_risk_probability=0.29,
                regime_transition_probability=0.21,
                regime_confidence=0.55,
                regime_freshness="FRESH",
                available=True,
            ),
            "funnel": {
                "markets_scanned": {"count": 42, "available": True},
                "liquidity": {"count": 18, "available": True},
                "data_quality": {"count": 11, "available": True},
                "ai_analysis": {"count": 7, "available": True},
                "cost_blocked": {"count": 2, "available": True},
                "risk_blocked": {"count": 1, "available": True},
            },
            "why_suggested": [
                "Public momentum softens into mixed regime",
                "Liquidity ok but event-risk window open",
            ],
            "supporting": [
                EvidenceItemDto(
                    evidence_summary="Short-horizon public momentum still constructive",
                    evidence_polarity="SUPPORTING",
                    evidence_freshness="FRESH",
                    source_label="PUBLIC_MARKET",
                    as_of=FIXTURE_AS_OF,
                ),
            ],
            "contradicting": [
                EvidenceItemDto(
                    evidence_summary="Elevated event-risk calendar cluster",
                    evidence_polarity="CONTRADICTING",
                    evidence_freshness="FRESH",
                    source_label="PUBLIC_CALENDAR",
                    as_of=FIXTURE_AS_OF,
                ),
            ],
            "uncertainty_band": "MEDIUM",
            "abstention_reason": None,
            "strategy_expert_label": "DEFENSIVE_NO_TRADE",
            "lesson_applied_label": "LESSON_APPLIED",
            "similar": SimilarCaseSummaryDto(
                similar_case_summary="4 similar public cases favored WAIT under mixed regime",
                similar_case_count=4,
                similar_case_overlap_band="MEDIUM",
                win_rate=None,  # never fabricate a 60% guarantee
                available=True,
                guarantee_claimed=False,
            ),
            "actually_ordered": False,
            "order_fill_claimed": False,
        },
        {
            "case_id": "mi_demo_long_ready_002",
            "symbol": "ETHUSDT",
            "decision_id": "pub_dec_mi_long_002",
            "lifecycle_state": "READY",
            "uxa_lifecycle": "MONITORING",
            "posture": "LONG",
            "mode": "DEMO_DATA",
            "data_freshness": "DEMO_DATA",
            "regime_label": "TREND_UP",
            "regime": RegimeProbabilitiesDto(
                strong_bull_probability=0.52,
                strong_bear_probability=0.14,
                volatility_expansion_probability=0.28,
                liquidity_stress_probability=0.11,
                long_crowding_probability=0.24,
                correlation_breakdown_probability=0.09,
                event_risk_probability=0.18,
                regime_transition_probability=0.16,
                regime_confidence=0.61,
                regime_freshness="FRESH",
                available=True,
            ),
            "funnel": {
                "markets_scanned": {"count": 55, "available": True},
                "liquidity": {"count": 30, "available": True},
                "data_quality": {"count": 22, "available": True},
                "ai_analysis": {"count": 14, "available": True},
                "cost_blocked": {"count": 0, "available": True},
                "risk_blocked": {"count": 0, "available": True},
            },
            "why_suggested": [
                "Trend-up regime probability leads peers",
                "Cost and risk gates clear in staging fixture",
            ],
            "supporting": [
                EvidenceItemDto(
                    evidence_summary="Public trend alignment across listed horizons",
                    evidence_polarity="SUPPORTING",
                    evidence_freshness="FRESH",
                    source_label="PUBLIC_MARKET",
                    as_of=FIXTURE_AS_OF,
                ),
            ],
            "contradicting": [
                EvidenceItemDto(
                    evidence_summary="Crowding probability elevated vs quiet baseline",
                    evidence_polarity="CONTRADICTING",
                    evidence_freshness="FRESH",
                    source_label="PUBLIC_MARKET",
                    as_of=FIXTURE_AS_OF,
                ),
            ],
            "uncertainty_band": "LOW",
            "abstention_reason": None,
            "strategy_expert_label": "TREND",
            "lesson_applied_label": "LESSON_CANDIDATE",
            "similar": SimilarCaseSummaryDto(
                similar_case_summary="Similar-case sample exists; no win-rate guarantee published",
                similar_case_count=6,
                similar_case_overlap_band="MEDIUM",
                win_rate=None,
                available=True,
                guarantee_claimed=False,
            ),
            "actually_ordered": False,  # READY suggestion — not a filled order
            "order_fill_claimed": False,
        },
        {
            "case_id": "mi_demo_abstain_003",
            "symbol": "SOLUSDT",
            "decision_id": "pub_dec_mi_abstain_003",
            "lifecycle_state": "ABSTAINED",
            "uxa_lifecycle": "ABSTAINED",
            "posture": "ABSTAIN",
            "mode": "DEMO_DATA",
            "data_freshness": "DEMO_DATA",
            "regime_label": "STRESS",
            "regime": RegimeProbabilitiesDto(
                strong_bull_probability=0.12,
                strong_bear_probability=0.44,
                volatility_expansion_probability=0.63,
                liquidity_stress_probability=0.58,
                long_crowding_probability=0.41,
                correlation_breakdown_probability=0.37,
                event_risk_probability=0.49,
                regime_transition_probability=0.40,
                regime_confidence=0.57,
                regime_freshness="FRESH",
                available=True,
            ),
            "funnel": {
                "markets_scanned": {"count": 40, "available": True},
                "liquidity": {"count": 9, "available": True},
                "data_quality": {"count": 6, "available": True},
                "ai_analysis": {"count": 4, "available": True},
                "cost_blocked": {"count": 1, "available": True},
                "risk_blocked": {"count": 3, "available": True},
            },
            "why_suggested": [
                "Abstain — liquidity stress and contradicting evidence dominate",
            ],
            "supporting": [],
            "contradicting": [
                EvidenceItemDto(
                    evidence_summary="Liquidity stress probability elevated",
                    evidence_polarity="CONTRADICTING",
                    evidence_freshness="FRESH",
                    source_label="PUBLIC_MARKET",
                    as_of=FIXTURE_AS_OF,
                ),
                EvidenceItemDto(
                    evidence_summary="Correlation breakdown risk active",
                    evidence_polarity="CONTRADICTING",
                    evidence_freshness="FRESH",
                    source_label="PUBLIC_MARKET",
                    as_of=FIXTURE_AS_OF,
                ),
            ],
            "uncertainty_band": "HIGH",
            "abstention_reason": "Liquidity stress + contradicting evidence exceed publish band",
            "strategy_expert_label": "DEFENSIVE_NO_TRADE",
            "lesson_applied_label": "LESSON_BLOCKED",
            "similar": SimilarCaseSummaryDto(
                similar_case_summary="Similar stress cases historically favored ABSTAIN",
                similar_case_count=5,
                similar_case_overlap_band="HIGH",
                win_rate=None,
                available=True,
                guarantee_claimed=False,
            ),
            "actually_ordered": False,
            "order_fill_claimed": False,
        },
        {
            "case_id": "mi_unavailable_004",
            "symbol": "BNBUSDT",
            "decision_id": "pub_dec_mi_unavail_004",
            "lifecycle_state": "UNAVAILABLE",
            "uxa_lifecycle": "UNAVAILABLE",
            "posture": "WAIT",
            "mode": "DEMO_DATA",
            "data_freshness": "UNAVAILABLE",
            "regime_label": "UNAVAILABLE",
            "regime": RegimeProbabilitiesDto(available=False, regime_freshness="UNAVAILABLE"),
            "funnel": {
                "markets_scanned": {"count": None, "available": False},
                "liquidity": {"count": None, "available": False},
                "data_quality": {"count": None, "available": False},
                "ai_analysis": {"count": None, "available": False},
                "cost_blocked": {"count": None, "available": False},
                "risk_blocked": {"count": None, "available": False},
            },
            "why_suggested": [],
            "supporting": [],
            "contradicting": [],
            "uncertainty_band": "UNAVAILABLE",
            "abstention_reason": "Source unavailable — fail closed",
            "strategy_expert_label": "UNAVAILABLE",
            "lesson_applied_label": "UNAVAILABLE",
            "similar": SimilarCaseSummaryDto(
                similar_case_summary="UNAVAILABLE",
                similar_case_count=None,
                similar_case_overlap_band="UNAVAILABLE",
                win_rate=None,
                available=False,
                guarantee_claimed=False,
            ),
            "actually_ordered": None,  # unknown — display UNAVAILABLE, not false-as-zero theatre
            "order_fill_claimed": False,
        },
        {
            "case_id": "mi_replay_005",
            "symbol": "BTCUSDT",
            "decision_id": "pub_dec_mi_replay_005",
            "lifecycle_state": "HISTORICAL_REPLAY",
            "uxa_lifecycle": "OUTCOME_REVIEW",
            "posture": "SHORT",
            "mode": "HISTORICAL_REPLAY",
            "data_freshness": "STALE",
            "regime_label": "TREND_DOWN",
            "regime": RegimeProbabilitiesDto(
                strong_bull_probability=0.18,
                strong_bear_probability=0.49,
                volatility_expansion_probability=0.33,
                liquidity_stress_probability=0.20,
                long_crowding_probability=0.15,
                correlation_breakdown_probability=0.12,
                event_risk_probability=0.22,
                regime_transition_probability=0.19,
                regime_confidence=0.50,
                regime_freshness="STALE",
                available=True,
            ),
            "funnel": {
                "markets_scanned": {"count": 30, "available": True},
                "liquidity": {"count": 12, "available": True},
                "data_quality": {"count": 10, "available": True},
                "ai_analysis": {"count": 8, "available": True},
                "cost_blocked": {"count": 0, "available": True},
                "risk_blocked": {"count": 1, "available": True},
            },
            "why_suggested": [
                "Historical replay suggestion only — not live market action",
            ],
            "supporting": [
                EvidenceItemDto(
                    evidence_summary="Replay bearish structure on recorded window",
                    evidence_polarity="SUPPORTING",
                    evidence_freshness="STALE",
                    source_label="HISTORICAL_REPLAY",
                    as_of=FIXTURE_AS_OF,
                ),
            ],
            "contradicting": [],
            "uncertainty_band": "MEDIUM",
            "abstention_reason": None,
            "strategy_expert_label": "MEAN_REVERSION",
            "lesson_applied_label": "NONE",
            "similar": SimilarCaseSummaryDto(
                similar_case_summary="Replay cohort summarized without performance guarantee",
                similar_case_count=2,
                similar_case_overlap_band="LOW",
                win_rate=None,
                available=True,
                guarantee_claimed=False,
            ),
            "actually_ordered": False,
            "order_fill_claimed": False,
        },
    ]
