/**
 * NEXUS-EXPERIENCE-1B — Personal experience context: THEME (system/light/dark),
 * VIEW MODE (simple/standard/pro — presentation density, NOT authorization), and
 * LOCALE (zh-TW/en-US/ja-JP/ko-KR, one active language). Preferences are
 * non-sensitive local UI state; backend entitlements remain authoritative.
 */
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

/* ---------------- theme ---------------- */
export type ThemeMode = "system" | "light" | "dark";
const THEME_KEY = "nexus.member.theme";
function applyTheme(m: ThemeMode) {
  const el = document.documentElement;
  if (m === "system") el.removeAttribute("data-theme");
  else el.setAttribute("data-theme", m);
}

/* ---------------- view mode (density, not auth) ---------------- */
export type ViewMode = "simple" | "standard" | "pro";
const VIEW_KEY = "nexus.member.view";

/* ---------------- locale ---------------- */
export const LOCALES = ["zh-TW", "en-US", "ja-JP", "ko-KR"] as const;
export type Locale = (typeof LOCALES)[number];
export const LOCALE_NAMES: Record<Locale, string> = { "zh-TW": "繁體中文", "en-US": "English", "ja-JP": "日本語", "ko-KR": "한국어" };
const LOCALE_KEY = "nexus.member.locale";

type Dict = Record<string, string>;
const M: Record<Locale, Dict> = {
  "zh-TW": {
    today: "今日", view: "檢視", simple: "簡易", standard: "標準", pro: "專業",
    theme: "主題", sys: "跟隨系統", light: "淺色", dark: "深色", lang: "語言",
    market_state: "市場狀態", market_risk: "市場風險", regime: "市場狀態",
    what_matters: "現在值得注意", why: "為什麼？", no_attention: "目前市場平穩，沒有需要特別注意的項目。",
    watchlist: "我的關注", watchlist_empty: "尚未加入關注資產。",
    latest_intel: "最新情報", intel_soon: "新聞與社群情報即將推出（尚未取得授權資料）。",
    brief: "今日市場簡報", brief_note: "由後端規則生成，非 AI。僅供參考，非投資建議。",
    cmd: "搜尋 BTC、ETH、新聞、機構，或直接問 NEXUS…",
    loading: "載入中…", unavailable: "暫不可用", stale: "資料延遲",
    r_contained: "受控", r_moderate: "中等", r_elevated: "偏高",
    v_low: "偏低", v_moderate: "中等", v_high: "偏高",
    attn_vol_high: "波動增加，走勢較不穩定", attn_range: "24H 區間擴大", attn_stable: "波動與區間受控",
    source: "來源 · 交易所市場",
    nav_overview: "總覽", nav_markets: "市場排行", nav_intel: "智慧分析", nav_watchlist: "我的觀察",
    nav_alerts: "風險提醒", nav_plans: "會員方案", nav_account: "帳號設定",
    m_home: "首頁", m_markets: "市場", m_watch: "觀察", m_alerts: "提醒", m_me: "我的",
    promo_title: "進階版 會員專屬", promo_body: "解鎖更深排行、即時風險與完整證據深度。", promo_cta: "升級方案",
    live_label: "即時行情", data_delayed: "資料延遲",
  },
  "en-US": {
    today: "Today", view: "View", simple: "Simple", standard: "Standard", pro: "Pro",
    theme: "Theme", sys: "System", light: "Light", dark: "Dark", lang: "Language",
    market_state: "Market state", market_risk: "Market risk", regime: "Regime",
    what_matters: "What matters now", why: "Why?", no_attention: "Markets are calm — nothing needs special attention right now.",
    watchlist: "Watchlist", watchlist_empty: "No assets in your watchlist yet.",
    latest_intel: "Latest intelligence", intel_soon: "News & social intelligence is coming soon (no licensed data yet).",
    brief: "Today's market brief", brief_note: "Generated by backend rules — not AI. Informational, not investment advice.",
    cmd: "Search BTC, ETH, news, institutions, or ask NEXUS…",
    loading: "Loading…", unavailable: "Unavailable", stale: "Delayed",
    r_contained: "Contained", r_moderate: "Moderate", r_elevated: "Elevated",
    v_low: "Low", v_moderate: "Moderate", v_high: "High",
    attn_vol_high: "Volatility rising, less stable", attn_range: "24H range expanding", attn_stable: "Volatility and range are contained",
    source: "Source · Exchange market",
    nav_overview: "Overview", nav_markets: "Markets", nav_intel: "Intelligence", nav_watchlist: "Watchlist",
    nav_alerts: "Alerts", nav_plans: "Membership", nav_account: "Account",
    m_home: "Home", m_markets: "Markets", m_watch: "Watchlist", m_alerts: "Alerts", m_me: "Account",
    promo_title: "Advanced membership", promo_body: "Unlock deeper rankings, live risk, and full evidence depth.", promo_cta: "Upgrade",
    live_label: "Live market", data_delayed: "Delayed",
  },
  "ja-JP": {
    today: "本日", view: "表示", simple: "シンプル", standard: "標準", pro: "プロ",
    theme: "テーマ", sys: "システム", light: "ライト", dark: "ダーク", lang: "言語",
    market_state: "市場状態", market_risk: "市場リスク", regime: "市場状態",
    what_matters: "いま注目すべきこと", why: "なぜ？", no_attention: "市場は落ち着いており、特に注意すべき項目はありません。",
    watchlist: "ウォッチリスト", watchlist_empty: "ウォッチリストはまだ空です。",
    latest_intel: "最新インテリジェンス", intel_soon: "ニュース・ソーシャル情報は近日公開（未ライセンス）。",
    brief: "本日の市場ブリーフ", brief_note: "バックエンドのルールで生成（AIではありません）。投資助言ではありません。",
    cmd: "BTC、ETH、ニュース、機関を検索、または NEXUS に質問…",
    loading: "読み込み中…", unavailable: "利用不可", stale: "遅延",
    r_contained: "抑制", r_moderate: "中", r_elevated: "高",
    v_low: "低", v_moderate: "中", v_high: "高",
    attn_vol_high: "ボラティリティ上昇、不安定", attn_range: "24H レンジ拡大", attn_stable: "ボラティリティとレンジは抑制",
    source: "ソース · 取引所マーケット",
    nav_overview: "概要", nav_markets: "市場ランキング", nav_intel: "インテリジェンス", nav_watchlist: "ウォッチリスト",
    nav_alerts: "アラート", nav_plans: "プラン", nav_account: "アカウント",
    m_home: "ホーム", m_markets: "市場", m_watch: "ウォッチ", m_alerts: "通知", m_me: "アカウント",
    promo_title: "アドバンス会員", promo_body: "より深いランキング、リアルタイムのリスク、完全な根拠を解放。", promo_cta: "アップグレード",
    live_label: "ライブ市場", data_delayed: "遅延",
  },
  "ko-KR": {
    today: "오늘", view: "보기", simple: "심플", standard: "표준", pro: "프로",
    theme: "테마", sys: "시스템", light: "라이트", dark: "다크", lang: "언어",
    market_state: "시장 상태", market_risk: "시장 리스크", regime: "시장 상태",
    what_matters: "지금 주목할 것", why: "왜?", no_attention: "시장이 안정적이며 특별히 주의할 항목이 없습니다.",
    watchlist: "관심목록", watchlist_empty: "관심목록이 비어 있습니다.",
    latest_intel: "최신 인텔리전스", intel_soon: "뉴스·소셜 인텔리전스 곧 출시 (미라이선스).",
    brief: "오늘의 시장 브리핑", brief_note: "백엔드 규칙으로 생성 (AI 아님). 투자 조언 아님.",
    cmd: "BTC, ETH, 뉴스, 기관 검색 또는 NEXUS에 질문…",
    loading: "불러오는 중…", unavailable: "사용 불가", stale: "지연",
    r_contained: "통제", r_moderate: "보통", r_elevated: "높음",
    v_low: "낮음", v_moderate: "보통", v_high: "높음",
    attn_vol_high: "변동성 상승, 불안정", attn_range: "24H 범위 확대", attn_stable: "변동성과 범위 통제",
    source: "출처 · 거래소 마켓",
    nav_overview: "개요", nav_markets: "마켓 랭킹", nav_intel: "인텔리전스", nav_watchlist: "관심목록",
    nav_alerts: "알림", nav_plans: "멤버십", nav_account: "계정",
    m_home: "홈", m_markets: "마켓", m_watch: "관심", m_alerts: "알림", m_me: "계정",
    promo_title: "어드밴스 멤버십", promo_body: "더 깊은 랭킹, 실시간 리스크, 완전한 근거를 잠금 해제.", promo_cta: "업그레이드",
    live_label: "실시간 시세", data_delayed: "지연",
  },
};

type Ctx = {
  theme: ThemeMode; resolvedTheme: "light" | "dark"; setTheme: (m: ThemeMode) => void;
  view: ViewMode; setView: (v: ViewMode) => void;
  locale: Locale; setLocale: (l: Locale) => void; t: (k: string) => string;
};
const ExpCtx = createContext<Ctx | null>(null);

function read<T extends string>(key: string, ok: readonly string[], fallback: T): T {
  try { const v = localStorage.getItem(key); if (v && ok.includes(v)) return v as T; } catch { /* ignore */ }
  return fallback;
}

export function NexusExperienceProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<ThemeMode>(() => read(THEME_KEY, ["system", "light", "dark"], "system"));
  const [sysDark, setSysDark] = useState(() => typeof window !== "undefined" && !!window.matchMedia?.("(prefers-color-scheme: dark)").matches);
  const [view, setViewState] = useState<ViewMode>(() => read(VIEW_KEY, ["simple", "standard", "pro"], "simple"));
  const [locale, setLocaleState] = useState<Locale>(() => read(LOCALE_KEY, LOCALES, "zh-TW"));

  useEffect(() => { applyTheme(theme); try { localStorage.setItem(THEME_KEY, theme); } catch { /* */ } }, [theme]);
  useEffect(() => { try { localStorage.setItem(VIEW_KEY, view); } catch { /* */ } }, [view]);
  useEffect(() => { document.documentElement.lang = locale; try { localStorage.setItem(LOCALE_KEY, locale); } catch { /* */ } }, [locale]);
  useEffect(() => {
    const mq = window.matchMedia?.("(prefers-color-scheme: dark)"); if (!mq) return;
    const h = () => setSysDark(mq.matches); mq.addEventListener?.("change", h); return () => mq.removeEventListener?.("change", h);
  }, []);

  const resolvedTheme = theme === "system" ? (sysDark ? "dark" : "light") : theme;
  const t = useCallback((k: string) => M[locale][k] ?? M["zh-TW"][k] ?? k, [locale]);
  const value = useMemo<Ctx>(() => ({
    theme, resolvedTheme, setTheme: setThemeState, view, setView: setViewState,
    locale, setLocale: setLocaleState, t,
  }), [theme, resolvedTheme, view, locale, t]);
  return <ExpCtx.Provider value={value}>{children}</ExpCtx.Provider>;
}

export function useExperience(): Ctx {
  const c = useContext(ExpCtx);
  if (!c) throw new Error("useExperience requires NexusExperienceProvider");
  return c;
}
