"""Edge Research V3 — pre-registered economic redesign hypotheses.

Wave V2 (9 hyps) is CONSUMED_NO_VALIDATED_COHORT. New IDs only.
Created before evaluation — do not add variants after seeing results.
"""
from __future__ import annotations

from typing import Any

RESEARCH_WAVE_V2_STATUS = "CONSUMED_NO_VALIDATED_COHORT"
V2_COMMIT = "58e8c95b96b2a652bbcdeee11c84b2331d0387c0"

HYPOTHESES_V3: list[dict[str, Any]] = [
    # --- H2 longer-horizon RANGE Sell ---
    {
        "hypothesis_id": "H2D_60m_upper_reject_to_vwap",
        "family": "H2",
        "variant": "D",
        "cohort": "VWAP_reversion|RANGE|Sell",
        "entry_logic": "60m_upper_boundary_rejection",
        "confirmation_logic": "240m RANGE; 60m near resistance; 15m bearish reject; target=60m VWAP",
        "exit_logic": "structural_tp_at_60m_vwap_or_mid; structural_stop_above_boundary",
        "churn_logic": "one_trade_per_boundary_event; cooldown=24 bars_15m",
        "parameter_values": {
            "htf_regime": "240",
            "structure_tf": "60",
            "entry_tf": "15",
            "min_move_to_cost": 2.5,
            "cooldown_15m_bars": 24,
            "min_holding_expectation_bars": 8,
        },
        "reason": "Prior H2 median hold ~5×15m; need larger structural displacement to VWAP",
        "expected_failure_mode": "COST_DOMINATED_CHURN or TARGET_UNREACHABLE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    {
        "hypothesis_id": "H2E_240m_range_60m_extreme_15m_reversal",
        "family": "H2",
        "variant": "E",
        "cohort": "VWAP_reversion|RANGE|Sell",
        "entry_logic": "240m_range_plus_60m_deviation_extreme",
        "confirmation_logic": "240m RANGE persistent; 60m dist-to-VWAP extreme; 15m reversal",
        "exit_logic": "60m_midpoint_or_vwap_target",
        "churn_logic": "one_per_extreme; cooldown=32",
        "parameter_values": {
            "htf_regime": "240",
            "structure_tf": "60",
            "entry_tf": "15",
            "min_vwap_dist_60m": 0.006,
            "min_move_to_cost": 2.8,
            "cooldown_15m_bars": 32,
            "min_holding_expectation_bars": 12,
        },
        "reason": "Larger 60m deviation before entry to improve gross_move/cost",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE or range_break",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    {
        "hypothesis_id": "H2F_failed_upside_break_reclaim",
        "family": "H2",
        "variant": "F",
        "cohort": "VWAP_reversion|RANGE|Sell",
        "entry_logic": "failed_upside_breakout_returning_inside_60m_range",
        "confirmation_logic": "pierce above 60m high then close back inside; 240m still RANGE",
        "exit_logic": "60m_vwap_or_range_mid",
        "churn_logic": "level_consumed; cooldown=28",
        "parameter_values": {
            "htf_regime": "240",
            "structure_tf": "60",
            "entry_tf": "15",
            "min_move_to_cost": 2.5,
            "cooldown_15m_bars": 28,
            "min_holding_expectation_bars": 10,
        },
        "reason": "False breakout reclaim often offers clearer structural target than scalp fade",
        "expected_failure_mode": "ENTRY_TOO_LATE or COST_DOMINATED_CHURN",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    # --- H1 breakout timing ---
    {
        "hypothesis_id": "H1D_60m_support_break_15m_failed_retest",
        "family": "H1",
        "variant": "D",
        "cohort": "breakout|BREAKOUT|Sell",
        "entry_logic": "60m_support_break_then_15m_failed_retest",
        "confirmation_logic": "close below 60m swing low; failed reclaim on 15m; remaining target > cost*mult",
        "exit_logic": "next_60m_structural_support_target",
        "churn_logic": "one_per_level; cooldown=20",
        "parameter_values": {
            "min_move_to_cost": 2.5,
            "max_extension_atr_60m": 1.0,
            "cooldown_15m_bars": 20,
        },
        "reason": "Avoid entering after move exhausted; retest reduces false breaks",
        "expected_failure_mode": "COST_GATE starvation if target too close",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    {
        "hypothesis_id": "H1E_240m_bear_60m_compression_break",
        "family": "H1",
        "variant": "E",
        "cohort": "breakout|BREAKOUT|Sell",
        "entry_logic": "240m_bearish_regime_plus_60m_compression_break",
        "confirmation_logic": "240m TRENDING_DOWN; 60m ATR contraction then break down",
        "exit_logic": "structural_geometry_with_60m_target_bias",
        "churn_logic": "cooldown=24",
        "parameter_values": {
            "min_move_to_cost": 2.8,
            "atr_contraction_max": 0.85,
            "cooldown_15m_bars": 24,
        },
        "reason": "Compression break in HTF bear regime should leave more remaining move",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    {
        "hypothesis_id": "H1F_15m_break_only_if_60m_target_covers_cost",
        "family": "H1",
        "variant": "F",
        "cohort": "breakout|BREAKOUT|Sell",
        "entry_logic": "15m_break_gated_by_60m_remaining_distance",
        "confirmation_logic": "15m break only when distance to next 60m support >= cost*mult",
        "exit_logic": "60m_support_target",
        "churn_logic": "cooldown=16; hard_economic_prefilter",
        "parameter_values": {
            "min_move_to_cost": 3.0,
            "cooldown_15m_bars": 16,
        },
        "reason": "Economic distance gate before Cost Gate — fewer late entries",
        "expected_failure_mode": "VALID_COST_GATE_BLOCK or INSUFFICIENT_SAMPLE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    # --- H3 trend continuation events ---
    {
        "hypothesis_id": "H3D_first_lh_after_240m_transition",
        "family": "H3",
        "variant": "D",
        "cohort": "trend_following|TRENDING_DOWN|Sell",
        "entry_logic": "first_lower_high_continuation_after_regime_transition",
        "confirmation_logic": "240m flips TRENDING_DOWN; first 60m LH; 15m continuation; no nearby support",
        "exit_logic": "structural_geometry",
        "churn_logic": "one_signal_per_trend_event",
        "parameter_values": {
            "min_move_to_cost": 2.5,
            "cooldown_15m_bars": 20,
            "event_window_60m_bars": 12,
        },
        "reason": "Event-based continuation instead of dense scanning",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    {
        "hypothesis_id": "H3E_60m_pullback_reject_240m_down",
        "family": "H3",
        "variant": "E",
        "cohort": "trend_following|TRENDING_DOWN|Sell",
        "entry_logic": "60m_pullback_rejection_in_240m_downtrend",
        "confirmation_logic": "240m down; 60m pullback to SMA/resistance reject; 15m sell trigger",
        "exit_logic": "structural_geometry",
        "churn_logic": "one_per_pullback",
        "parameter_values": {
            "min_move_to_cost": 2.5,
            "cooldown_15m_bars": 24,
        },
        "reason": "Pullback entries should improve remaining move vs late chase",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE or ENTRY_TOO_LATE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    {
        "hypothesis_id": "H3F_continuation_after_vol_contraction",
        "family": "H3",
        "variant": "F",
        "cohort": "trend_following|TRENDING_DOWN|Sell",
        "entry_logic": "trend_continuation_after_volatility_contraction",
        "confirmation_logic": "240m down; 60m ATR contracts then expands down; 15m confirm",
        "exit_logic": "structural_geometry",
        "churn_logic": "cooldown=28",
        "parameter_values": {
            "min_move_to_cost": 2.8,
            "atr_contraction_max": 0.9,
            "cooldown_15m_bars": 28,
        },
        "reason": "Contraction-expansion continuation often leaves cleaner displacement",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": False,
    },
    # --- Enriched (max 2 per family) — require microstructure ---
    {
        "hypothesis_id": "H2G_range_sell_no_oi_breakout",
        "family": "H2",
        "variant": "G",
        "cohort": "VWAP_reversion|RANGE|Sell",
        "entry_logic": "H2D_plus_no_oi_expansion",
        "confirmation_logic": "H2D setup + OI not expanding (breakout risk)",
        "exit_logic": "60m_vwap_target",
        "churn_logic": "same as H2D",
        "parameter_values": {"min_move_to_cost": 2.5, "oi_expand_max_pct": 0.02, "cooldown_15m_bars": 24},
        "reason": "OI expansion may mark range break risk",
        "expected_failure_mode": "DATA_UNAVAILABLE or INSUFFICIENT_SAMPLE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": True,
        "enrichment": ["open_interest"],
    },
    {
        "hypothesis_id": "H1G_breakout_sell_with_sell_imbalance",
        "family": "H1",
        "variant": "G",
        "cohort": "breakout|BREAKOUT|Sell",
        "entry_logic": "H1D_plus_funding_not_crowded",
        "confirmation_logic": "H1D + funding not extremely positive (crowded long squeeze risk opposite)",
        "exit_logic": "structural",
        "churn_logic": "same as H1D",
        "parameter_values": {"min_move_to_cost": 2.5, "funding_abs_max": 0.001, "cooldown_15m_bars": 20},
        "reason": "Funding/positioning filter for breakdown quality",
        "expected_failure_mode": "DATA_UNAVAILABLE or VALID_COST_GATE_BLOCK",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": True,
        "enrichment": ["funding"],
    },
    {
        "hypothesis_id": "H3G_trend_down_oi_continuation",
        "family": "H3",
        "variant": "G",
        "cohort": "trend_following|TRENDING_DOWN|Sell",
        "entry_logic": "H3E_plus_oi_continuation_class",
        "confirmation_logic": "H3E + OI behavior not collapsing (coverage dependent)",
        "exit_logic": "structural",
        "churn_logic": "same as H3E",
        "parameter_values": {"min_move_to_cost": 2.5, "cooldown_15m_bars": 24},
        "reason": "OI continuation class when available",
        "expected_failure_mode": "DATA_UNAVAILABLE or INSUFFICIENT_SAMPLE",
        "training_period": "v3_outer_fold_train",
        "validation_period": "v3_outer_fold_inner_val",
        "created_before_evaluation": True,
        "requires_microstructure": True,
        "enrichment": ["open_interest", "funding"],
    },
]

assert all(h["created_before_evaluation"] is True for h in HYPOTHESES_V3)
assert len([h for h in HYPOTHESES_V3 if h["family"] == "H2" and not h.get("requires_microstructure")]) == 3
assert len([h for h in HYPOTHESES_V3 if h["family"] == "H1" and not h.get("requires_microstructure")]) == 3
assert len([h for h in HYPOTHESES_V3 if h["family"] == "H3" and not h.get("requires_microstructure")]) == 3
