"""Edge Research V2 — pre-registered deep cohort hypotheses (max 9).

Written BEFORE evaluation. Do not add variants after seeing validation results.
"""
from __future__ import annotations

from typing import Any

# --- Locked before evaluation ---
HYPOTHESES_V2: list[dict[str, Any]] = [
    {
        "hypothesis_id": "H1A_breakout_sell_close_confirmed",
        "cohort": "breakout|BREAKOUT|Sell",
        "family": "H1",
        "variant": "A",
        "entry_logic": "close_confirmed_break_below_prior_swing_low",
        "confirmation_logic": "close < prior_low AND volume > median*1.2 AND displacement > cost_proxy",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "same_symbol_cooldown=12; one_signal_per_structure_level; min_displacement",
        "parameter_values": {
            "vol_mult": 1.2,
            "min_disp_atr": 0.35,
            "max_extension_atr": 1.4,
            "cooldown_bars": 12,
        },
        "reason": "Gross edge destroyed by cost — improve selection via close+volume confirmation",
        "expected_failure_mode": "COST_DOMINATED_CHURN or false breakouts",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H1B_breakout_sell_failed_retest",
        "cohort": "breakout|BREAKOUT|Sell",
        "family": "H1",
        "variant": "B",
        "entry_logic": "break_then_failed_retest_of_broken_level",
        "confirmation_logic": "prior break + reclaim attempt fails (close back below level)",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "cooldown=16; no_duplicate_direction; level_consumed",
        "parameter_values": {
            "retest_lookback": 8,
            "vol_mult": 1.0,
            "min_disp_atr": 0.25,
            "max_extension_atr": 1.6,
            "cooldown_bars": 16,
        },
        "reason": "Retest failure may reduce false breakouts and raise gross_move/cost",
        "expected_failure_mode": "ENTRY_SELECTION_FAILURE if retest rare",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H1C_breakout_sell_vol_confirm",
        "cohort": "breakout|BREAKOUT|Sell",
        "family": "H1",
        "variant": "C",
        "entry_logic": "breakout_with_volatility_and_volume_expansion",
        "confirmation_logic": "ATR percentile high + volume expansion + not overextended",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "cooldown=10; max_spread_bucket; min_expected_hold=3",
        "parameter_values": {
            "vol_mult": 1.35,
            "atr_vs_median_min": 1.25,
            "min_disp_atr": 0.4,
            "max_extension_atr": 1.2,
            "cooldown_bars": 10,
        },
        "reason": "Require expansion so expected move can cover round-trip cost",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE or COST_DOMINATED_CHURN",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H2A_vwap_sell_upper_rejection",
        "cohort": "VWAP_reversion|RANGE|Sell",
        "family": "H2",
        "variant": "A",
        "entry_logic": "upper_boundary_rejection_in_range",
        "confirmation_logic": "RANGE; price>VWAP; bearish rejection candle near resistance; no BREAKOUT",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "one_per_boundary; cooldown=14; block_narrow_range",
        "parameter_values": {
            "min_vwap_dist": 0.0025,
            "min_range_width_atr": 0.8,
            "cooldown_bars": 14,
        },
        "reason": "Improve mean-reversion selection to survive costs",
        "expected_failure_mode": "COST_DOMINATED_CHURN in narrow ranges",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H2B_vwap_sell_deviation_reversal",
        "cohort": "VWAP_reversion|RANGE|Sell",
        "family": "H2",
        "variant": "B",
        "entry_logic": "vwap_deviation_plus_momentum_loss",
        "confirmation_logic": "dist_above_VWAP>=threshold; last bar closes red; RANGE only",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "cooldown=12; suppress_trending_up_htf",
        "parameter_values": {
            "min_vwap_dist": 0.004,
            "min_range_width_atr": 0.6,
            "cooldown_bars": 12,
        },
        "reason": "Larger deviation increases return-to-mean vs cost",
        "expected_failure_mode": "TARGET_UNREACHABLE or range_break",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H2C_vwap_sell_extreme_contraction",
        "cohort": "VWAP_reversion|RANGE|Sell",
        "family": "H2",
        "variant": "C",
        "entry_logic": "range_extreme_with_volatility_contraction",
        "confirmation_logic": "near resistance; ATR contracting; RANGE; no expansion breakout",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "cooldown=18; block_if_atr_expanding",
        "parameter_values": {
            "min_vwap_dist": 0.003,
            "atr_contraction_max": 0.9,
            "min_range_width_atr": 0.7,
            "cooldown_bars": 18,
        },
        "reason": "Contraction-at-extreme may improve reward/cost before expansion",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H3A_trend_down_sell_structure",
        "cohort": "trend_following|TRENDING_DOWN|Sell",
        "family": "H3",
        "variant": "A",
        "entry_logic": "lh_ll_structure_in_trending_down",
        "confirmation_logic": "TRENDING_DOWN; lower_high+lower_low; momentum down; support not immediate",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "cooldown=8; min_disp_after_cost",
        "parameter_values": {
            "structure_lookback": 12,
            "min_disp_atr": 0.3,
            "cooldown_bars": 8,
        },
        "reason": "Prior n=5 insufficient — expand data, keep selection honest",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H3B_trend_down_sell_htf_aligned",
        "cohort": "trend_following|TRENDING_DOWN|Sell",
        "family": "H3",
        "variant": "B",
        "entry_logic": "ltf_trend_with_htf_60_240_alignment",
        "confirmation_logic": "15m TRENDING_DOWN AND 60m/240m bearish SMA alignment",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "cooldown=10; htf_required",
        "parameter_values": {
            "require_htf60": True,
            "require_htf240": True,
            "min_disp_atr": 0.25,
            "cooldown_bars": 10,
        },
        "reason": "HTF alignment should reduce counter-trend churn",
        "expected_failure_mode": "INSUFFICIENT_SAMPLE",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
    {
        "hypothesis_id": "H3C_trend_down_sell_momentum_fresh",
        "cohort": "trend_following|TRENDING_DOWN|Sell",
        "family": "H3",
        "variant": "C",
        "entry_logic": "trending_down_with_fresh_momentum_not_exhausted",
        "confirmation_logic": "TRENDING_DOWN; momentum window positive for shorts; ATR not collapsing; not at major swing low",
        "exit_logic": "structural_geometry_stop_tp",
        "churn_logic": "cooldown=12; skip_if_near_swing_low",
        "parameter_values": {
            "momentum_bars": 8,
            "min_disp_atr": 0.35,
            "swing_low_buffer_atr": 0.5,
            "cooldown_bars": 12,
        },
        "reason": "Avoid exhausted late-trend entries that fail cost",
        "expected_failure_mode": "ENTRY_SELECTION_FAILURE or INSUFFICIENT_SAMPLE",
        "training_period": "outer_fold_train",
        "validation_period": "outer_fold_inner_val",
        "created_before_evaluation": True,
    },
]

assert len(HYPOTHESES_V2) == 9
assert all(h["created_before_evaluation"] is True for h in HYPOTHESES_V2)

# Timeframe justification (holding duration driven, not performance mined)
TIMEFRAME_JUSTIFICATION = {
    "regime_htf": "240",
    "structure_htf": "60",
    "strategy_tf": "15",
    "intrabar": "15_adverse_first",
    "reason": (
        "Expected hold 30m–12h (2–48 bars on 15m). "
        "240m for regime direction; 60m for structure alignment; "
        "15m for candidate/entry and adverse-first fill resolution. "
        "1m omitted: holding horizon does not justify denser fill model cost."
    ),
}
