"""DEMO_AUTONOMOUS_6H_V2_BOUNDED_VALIDATION session constants."""
from __future__ import annotations

from backend.nexus_execution.cost_model import (
    DEFAULT_COST_UNCERTAINTY_BUFFER_RATE,
    DEFAULT_FUNDING_UNAVAILABLE_BUFFER_RATE,
    DEFAULT_TAKER_FEE,
)

SESSION_GATE_NAME = "DEMO_AUTONOMOUS_6H_V2_BOUNDED_VALIDATION"
# Legacy alias still recognized by start() for one-release compatibility.
SESSION_GATE_NAME_LEGACY = "DEMO_AUTONOMOUS_6H_BOUNDED_VALIDATION"
SESSION_DURATION_SEC = 6 * 60 * 60
CHECKPOINT_OFFSETS_SEC = (
    0,
    15 * 60,
    30 * 60,
    60 * 60,
    2 * 60 * 60,
    3 * 60 * 60,
    4 * 60 * 60,
    5 * 60 * 60,
    6 * 60 * 60,
)

MAX_CONCURRENT_POSITIONS = 1
MAX_PENDING_ORDERS = 1
MAX_TOTAL_ENTRY_ORDERS = 6
MAX_COMPLETED_TRADE_CASES = 6
MARGIN_PER_TRADE_CAP = 20.0
FIXED_LEVERAGE = 25
MARGIN_MODE = "ISOLATED"

MAX_SESSION_NET_LOSS = 10.0
MAX_SINGLE_TRADE_NET_LOSS = 3.0
MAX_CONSECUTIVE_LOSSES = 3
MAX_BAD_PROCESS_OUTCOMES = 1
MAX_UNPROTECTED = 0
MAX_DUPLICATE_ORDERS = 0
MAX_RECONCILIATION_INCIDENTS = 0
MAX_CONTROLLER_OWNERS = 1

ACCOUNT_SNAPSHOT_MAX_AGE_SEC = 30
PROTECTION_VERIFY_DEADLINE_SEC = 5
MAX_HOLD_SEC = 30 * 60
CYCLE_INTERVAL_SEC = 120
SUPERVISOR_POLL_SEC = 10

# Cost gate — floors must not be lowered. Rates from canonical cost_model.
TAKER_FEE_RATE_DEFAULT = float(DEFAULT_TAKER_FEE)  # used only after fee-rate fetch fails → BLOCK
MIN_NET_REWARD_TO_COST = 1.5
MIN_NET_REWARD_RISK_RATIO = 1.2
FUNDING_CONSERVATIVE_BUFFER_RATE = float(DEFAULT_FUNDING_UNAVAILABLE_BUFFER_RATE)
COST_UNCERTAINTY_BUFFER_RATE = float(DEFAULT_COST_UNCERTAINTY_BUFFER_RATE)

POLICY_VERSION = "demo-autonomous-6h-v2-bounded"
SCHEMA_VERSION = "demo_validation_session_v2"
DECISION_LABEL = "RULE_BASED"  # honest: no LLM claim
