"""DEMO_AUTONOMOUS_12H_V3_BOUNDED_VALIDATION policy — separate session from 6H V2."""
from __future__ import annotations

SESSION_GATE_NAME = "DEMO_AUTONOMOUS_12H_V3_BOUNDED_VALIDATION"
POLICY_VERSION = "demo-autonomous-12h-v3-bounded"
SCHEMA_VERSION = "demo_validation_session_v3"

SESSION_DURATION_SEC = 12 * 60 * 60
AUTOMATIC_EXTENSION = False
CYCLE_INTERVAL_SEC = 120
SUPERVISOR_POLL_SEC = 10

MAX_CONCURRENT_POSITIONS = 1
MAX_PENDING_ORDERS = 1
MAX_TOTAL_ENTRY_ORDERS = 10
MAX_COMPLETED_TRADE_CASES = 10
MARGIN_PER_TRADE_CAP = 20.0
MIN_MARGIN_IF_RISK_SAFE = 20.0
FIXED_LEVERAGE = 25
MARGIN_MODE = "ISOLATED"

MAX_SESSION_NET_LOSS = 15.0
MAX_SINGLE_TRADE_NET_LOSS = 3.0
MAX_CONSECUTIVE_LOSSES = 3
MAX_BAD_PROCESS_OUTCOMES = 1
MAX_UNPROTECTED = 0
MAX_DUPLICATE_ORDERS = 0
MAX_RECONCILIATION_INCIDENTS = 0
MAX_RUNTIME_STALLS = 0
MAX_CONTROLLER_OWNERS = 1

ACCOUNT_SNAPSHOT_MAX_AGE_SEC = 30
PROTECTION_VERIFY_DEADLINE_SEC = 5
MAX_HOLD_SEC = 30 * 60

MIN_NET_REWARD_TO_COST = 1.5
MIN_NET_REWARD_RISK_RATIO = 1.2

TAKER_FEE_RATE = 0.00055
MAKER_FEE_RATE = 0.00020
PRETRADE_ROUND_TRIP_FEE_RATE = 0.00110
FEE_REVIEW_BY = "2026-08-31"

# 12H must never reuse 6H session id / write window.
REQUIRES_SOURCE_6H_PASS = True
# PASS_WITH_FINDINGS alone is insufficient when entries_total==0;
# machine gate also requires autonomous_execution_observed / same-router probe.
ALLOWED_SOURCE_6H_RECOMMENDATIONS = frozenset(
    {
        "DEMO_AUTONOMOUS_6H_V2_PASS",
        "DEMO_AUTONOMOUS_6H_V2_PASS_WITH_FINDINGS",
    }
)
INCONCLUSIVE_6H_RECOMMENDATIONS = frozenset(
    {
        "DEMO_AUTONOMOUS_6H_V2_INCONCLUSIVE_NO_EXECUTION",
        "DEMO_AUTONOMOUS_6H_V2_FAILED",  # Runtime SoT for zero-entry sessions until enum ships live
    }
)

BLOCKING_6H_FINDINGS = frozenset(
    {
        "FEE_DATA_ABNORMAL",
        "GEOMETRY_FORMULA_ABNORMAL",
        "COST_GATE_ABNORMAL",
        "PROTECTION_DELAY",
        "RECONCILIATION_ABNORMAL",
        "DUPLICATE_INTENT",
        "RUNTIME_STALL",
        "RUNTIME_RESTART",
        "PERSISTENCE_LOSS",
        "DECISION_DELTA_MISCLASSIFIED",
    }
)

CHECKPOINT_OFFSETS_SEC = (
    15 * 60,
    30 * 60,
    60 * 60,
    2 * 60 * 60,
    4 * 60 * 60,
    6 * 60 * 60,
    8 * 60 * 60,
    10 * 60 * 60,
    12 * 60 * 60,
)
