MAX_CONFIDENCE_PENALTY = 0.4
LOSS_RATE_PENALTY_THRESHOLD = 0.55
CONSECUTIVE_LOSS_SOFT_BLOCK = 3
CONSECUTIVE_LOSS_HARD_BLOCK = 5
SYMBOL_COOLDOWN_LOSS_COUNT = 3
SYMBOL_COOLDOWN_WINDOW = 6
SYMBOL_COOLDOWN_SECONDS = 6 * 60 * 60
HIGH_LEVERAGE_FAILURE_THRESHOLD = 20
HIGH_LEVERAGE_PENALTY_STEP = 0.03
MAX_HIGH_LEVERAGE_PENALTY = 0.15
BASE_POSITION_SIZE_MULTIPLIER_FLOOR = 0.35
BASE_AGGRESSION_MULTIPLIER_FLOOR = 0.45
FAILURE_FOCUS_BLOCK_MAP = {
    "low_liquidity": "low_liquidity",
    "news_conflict": "news_conflict",
    "whale_reversal": "whale_conflict",
    "bad_market_regime": "market_regime",
}
