import os

RADAR_SCAN_SYMBOLS = (
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "1000PEPEUSDT",
    "BNBUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "LINKUSDT",
    "AVAXUSDT",
    "SUIUSDT",
    "TRXUSDT",
)

RADAR_MAX_CANDIDATES = 5
RADAR_MAX_WHALE_NOTES = 5
RADAR_SCAN_CACHE_SECONDS = int(float(os.getenv("NEXUS_RADAR_SCAN_CACHE_SECONDS", "25")))
RADAR_MIN_CANDIDATE_NOTIONAL = 15_000.0
