"""Liquid universe for RADAR scanning (Top-N by static list; exchange filter optional)."""

import os

RADAR_UNIVERSE_MAX_SYMBOLS = int(os.getenv("NEXUS_RADAR_UNIVERSE_MAX", "50"))
RADAR_UNIVERSE_MIN_NOTIONAL = float(os.getenv("NEXUS_RADAR_MIN_NOTIONAL", "15000"))

# Top liquid USDT perpetuals (static fallback when exchange ticker fetch unavailable)
TOP_LIQUIDITY_SYMBOLS = (
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "BNBUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "LINKUSDT",
    "AVAXUSDT",
    "SUIUSDT",
    "TRXUSDT",
    "1000PEPEUSDT",
    "LTCUSDT",
    "BCHUSDT",
    "DOTUSDT",
    "NEARUSDT",
    "APTUSDT",
    "FILUSDT",
    "ARBUSDT",
    "OPUSDT",
    "INJUSDT",
    "ATOMUSDT",
    "UNIUSDT",
    "ETCUSDT",
    "ICPUSDT",
    "TIAUSDT",
    "FETUSDT",
    "RENDERUSDT",
    "WLDUSDT",
    "SEIUSDT",
    "STXUSDT",
    "IMXUSDT",
    "RUNEUSDT",
    "AAVEUSDT",
    "GRTUSDT",
    "MKRUSDT",
    "SNXUSDT",
    "SANDUSDT",
    "MANAUSDT",
    "AXSUSDT",
    "EGLDUSDT",
    "THETAUSDT",
    "ALGOUSDT",
    "VETUSDT",
    "XLMUSDT",
    "HBARUSDT",
    "FTMUSDT",
    "CRVUSDT",
    "LDOUSDT",
    "ORDIUSDT",
    "JUPUSDT",
)
