BACKTEST_MIN_SAMPLE_SIZE = 6
BACKTEST_MIN_WIN_RATE = 0.35
BACKTEST_MAX_ALLOWED_RECENT_LOSSES = 4
BACKTEST_MAX_NEGATIVE_AVG_PNL = -2.5

SIMULATION_MAX_SPREAD_BPS = 18.0
SIMULATION_MIN_TOP5_NOTIONAL = 15000.0
SIMULATION_BLOCKED_REGIMES = {
    "extreme_volatility",
    "crash",
    "news_shock",
    "alert_red",
}

PAPER_MAX_RECENT_EXECUTION_ERRORS = 3
PAPER_MAX_RECENT_VALIDATION_BLOCKS = 4
PAPER_VALIDATION_WINDOW_SECONDS = 900

VALIDATION_MIN_APPROVAL_SCORE = 0.52
