"""Stage 4 context-unavailable skip decisions (no LLM, no mock)."""
from __future__ import annotations

import uuid
from typing import Any, Dict

from tools.research.bybit_demo_learning_common import utc_now_iso
from tools.research.stage4_ai_decision_agent import safety_constraints_from_env


def make_context_unavailable_decision(
    *,
    symbol: str,
    mode: str,
    market_context: Dict[str, Any],
    account_context: Dict[str, Any],
    error_reason: str = "symbol_unavailable_or_market_context_failed",
    open_positions: int = 0,
) -> Dict[str, Any]:
    sr = {
        "approved": False,
        "final_decision": "skip",
        "veto_reason": "missing_market_context",
        "action": "force_skip",
    }
    return {
        "decision_id": str(uuid.uuid4()),
        "created_at_utc": utc_now_iso(),
        "decision_source": "stage4_context_skip",
        "mode": mode,
        "model_name": None,
        "provider": None,
        "provider_chain": [],
        "provider_attempts": [],
        "fallback_used": False,
        "fallback_reason": None,
        "primary_provider": None,
        "primary_error": None,
        "is_mock_ai": False,
        "real_llm_used": False,
        "fallback_to_mock": False,
        "fallback_model_name": None,
        "prompt_hash": "",
        "symbol": symbol.upper(),
        "candidate_side": "NONE",
        "final_action": "skip",
        "confidence": 0.0,
        "position_size_suggestion": 0,
        "market_context": market_context,
        "account_context": account_context,
        "retrieved_patches": [],
        "recent_trade_results": [],
        "recent_reflections": [],
        "active_patch_count": 0,
        "patch_applied_before_decision": False,
        "current_open_positions": open_positions,
        "why_enter": "",
        "why_skip": error_reason,
        "side_reason": "",
        "confidence_reason": "",
        "risk_notes": [],
        "patch_awareness": "",
        "uncertainty": "high",
        "reasoning_summary": error_reason,
        "regime": market_context.get("regime", "unknown"),
        "decision_intent": "hard_skip",
        "missing_data": list(market_context.get("data_limitations") or []),
        "edge_factors": [],
        "risk_factors": [error_reason],
        "stage3_context_summary": {},
        "stage3_context_available": False,
        "stage3_context_reason": "context_skip",
        "recent_trade_results_count": 0,
        "recent_reflections_count": 0,
        "active_patches_count": 0,
        "patch_blocked": False,
        "patch_block_reason": "",
        "matched_patch_count": 0,
        "matched_patch_actions": [],
        "parse_error": False,
        "parse_error_type": None,
        "raw_content_empty": False,
        "market_context_unavailable": True,
        "market_context_error": error_reason,
        "safety_constraints": safety_constraints_from_env(),
        "risk_supervisor_result": sr,
        "final_decision": "skip",
        "order_sent": False,
    }
