"""Synthetic development fixtures for risk/capacity review (non-OOS)."""
from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Any

from backend.nexus_risk_capacity.constants import DEVELOPMENT_INTERVAL_ID, RANDOM_SEED


@dataclass(frozen=True, slots=True)
class SyntheticCandidate:
    candidate_id: str
    mechanism_family: str
    symbol: str
    side: str  # LONG | SHORT
    qty: Decimal
    entry_price: Decimal
    exit_price: Decimal
    sample_trade_count: int
    position_concentration: Decimal
    instrument_concentration: Decimal
    regime_concentration: Decimal
    assumed_max_drawdown: Decimal
    liquidation_distance_pct: Decimal
    missing_data: bool
    stale_data: bool
    data_age_sec: Decimal
    development_interval_id: str = DEVELOPMENT_INTERVAL_ID
    oos_consumed: bool = False
    evidence_class: str = "FIXTURE_SYNTHETIC_DEVELOPMENT_ONLY"


def build_synthetic_candidates(*, seed: int = RANDOM_SEED) -> list[SyntheticCandidate]:
    """Fixed deterministic fixture set — never treated as live edge evidence."""
    _ = seed
    # id, family, symbol, side, qty, entry, exit, n,
    # pos_c, inst_c, regime_c, mdd, liq_dist, missing, stale, age
    rows: list[tuple] = [
        (
            "RC01",
            "ORDER_FLOW_IMBALANCE",
            "BTCUSDT",
            "LONG",
            "0.010",
            "60000",
            "60120",
            40,
            "0.18",
            "0.22",
            "0.30",
            "0.08",
            "12.0",
            False,
            False,
            "30",
        ),
        (
            "RC02",
            "ABSORPTION",
            "BTCUSDT",
            "LONG",
            "0.020",
            "60000",
            "60080",
            36,
            "0.20",
            "0.25",
            "0.35",
            "0.10",
            "9.0",
            False,
            False,
            "45",
        ),
        (
            "RC03",
            "LIQUIDATION_CASCADE",
            "ETHUSDT",
            "SHORT",
            "0.50",
            "3200",
            "3188",
            28,
            "0.28",
            "0.30",
            "0.40",
            "0.12",
            "6.5",
            False,
            False,
            "20",
        ),
        (
            "RC04",
            "SPREAD_SHOCK",
            "ETHUSDT",
            "LONG",
            "0.40",
            "3200",
            "3205",
            24,
            "0.22",
            "0.28",
            "0.45",
            "0.15",
            "8.0",
            False,
            False,
            "55",
        ),
        (
            "RC05",
            "FUNDING_BASIS",
            "BTCUSDT",
            "LONG",
            "0.015",
            "60000",
            "60040",
            32,
            "0.25",
            "0.32",
            "0.38",
            "0.09",
            "11.0",
            False,
            False,
            "40",
        ),
        (
            "RC06",
            "CONCENTRATION_HOT",
            "SOLUSDT",
            "SHORT",
            "20",
            "140",
            "139.4",
            22,
            "0.48",
            "0.55",
            "0.70",
            "0.14",
            "7.0",
            False,
            False,
            "35",
        ),
        (
            "RC07",
            "DRAWDOWN_UNSAFE",
            "SOLUSDT",
            "LONG",
            "15",
            "140",
            "140.2",
            20,
            "0.20",
            "0.25",
            "0.40",
            "0.35",
            "10.0",
            False,
            False,
            "50",
        ),
        (
            "RC08",
            "LIQUIDATION_NEAR",
            "XRPUSDT",
            "LONG",
            "2000",
            "0.55",
            "0.552",
            26,
            "0.18",
            "0.22",
            "0.33",
            "0.10",
            "2.5",
            False,
            False,
            "25",
        ),
        (
            "RC09",
            "MISSING_DATA_BLOCK",
            "BTCUSDT",
            "LONG",
            "0.008",
            "60000",
            "60090",
            30,
            "0.15",
            "0.20",
            "0.30",
            "0.08",
            "14.0",
            True,
            False,
            "10",
        ),
        (
            "RC10",
            "STALE_DATA_BLOCK",
            "ETHUSDT",
            "LONG",
            "2.0",
            "3200",
            "3208",
            18,
            "0.16",
            "0.21",
            "0.32",
            "0.09",
            "13.0",
            False,
            True,
            "600",
        ),
        (
            "RC11",
            "LATENCY_FRAGILE",
            "BTCUSDT",
            "SHORT",
            "0.012",
            "60000",
            "59940",
            26,
            "0.19",
            "0.24",
            "0.36",
            "0.11",
            "8.5",
            False,
            False,
            "60",
        ),
        (
            "RC12",
            "LOW_EDGE_COST_DESTROY",
            "BTCUSDT",
            "LONG",
            "0.010",
            "60000",
            "60010",
            14,
            "0.17",
            "0.23",
            "0.34",
            "0.10",
            "9.5",
            False,
            False,
            "70",
        ),
        (
            "RC13",
            "CAPACITY_SIZE_FRAGILE",
            "ETHUSDT",
            "LONG",
            "3.5",
            "3200",
            "3206",
            20,
            "0.21",
            "0.27",
            "0.42",
            "0.13",
            "7.5",
            False,
            False,
            "48",
        ),
        (
            "RC14",
            "QUEUE_SENSITIVE_MAKER",
            "BTCUSDT",
            "LONG",
            "0.009",
            "60000",
            "60070",
            28,
            "0.14",
            "0.19",
            "0.28",
            "0.07",
            "15.0",
            False,
            False,
            "22",
        ),
    ]
    out: list[SyntheticCandidate] = []
    for row in rows:
        (
            cid,
            fam,
            sym,
            side,
            qty,
            entry,
            exit_,
            n,
            pos_c,
            inst_c,
            regime_c,
            mdd,
            liq,
            missing,
            stale,
            age,
        ) = row
        out.append(
            SyntheticCandidate(
                candidate_id=cid,
                mechanism_family=fam,
                symbol=sym,
                side=side,
                qty=Decimal(qty),
                entry_price=Decimal(entry),
                exit_price=Decimal(exit_),
                sample_trade_count=n,
                position_concentration=Decimal(pos_c),
                instrument_concentration=Decimal(inst_c),
                regime_concentration=Decimal(regime_c),
                assumed_max_drawdown=Decimal(mdd),
                liquidation_distance_pct=Decimal(liq),
                missing_data=bool(missing),
                stale_data=bool(stale),
                data_age_sec=Decimal(age),
            )
        )
    return out


def candidate_as_dict(c: SyntheticCandidate) -> dict[str, Any]:
    return {
        "candidate_id": c.candidate_id,
        "mechanism_family": c.mechanism_family,
        "symbol": c.symbol,
        "side": c.side,
        "qty": format(c.qty, "f"),
        "entry_price": format(c.entry_price, "f"),
        "exit_price": format(c.exit_price, "f"),
        "sample_trade_count": c.sample_trade_count,
        "position_concentration": format(c.position_concentration, "f"),
        "instrument_concentration": format(c.instrument_concentration, "f"),
        "regime_concentration": format(c.regime_concentration, "f"),
        "assumed_max_drawdown": format(c.assumed_max_drawdown, "f"),
        "liquidation_distance_pct": format(c.liquidation_distance_pct, "f"),
        "missing_data": c.missing_data,
        "stale_data": c.stale_data,
        "data_age_sec": format(c.data_age_sec, "f"),
        "development_interval_id": c.development_interval_id,
        "oos_consumed": c.oos_consumed,
        "evidence_class": c.evidence_class,
        "profitability_claimed": False,
        "qualified_claimed": False,
        "strategy_promoted": False,
        "strategy_selected": False,
    }
