"""Small legal fixture sources for V17-A Data Source Registry.

Legal only: official APIs, founder-authorized commercial APIs (under review),
self-hosted/public chain, commercial-ok datasets. No paywalled scrapes.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from backend.nexus_data_source_registry.constants import (
    FIXTURES_REL,
    LANE,
    SCHEMA,
    SCHEMA_VERSION,
)


def _src(**overrides: Any) -> dict[str, Any]:
    base: dict[str, Any] = {
        "source_id": "placeholder",
        "provider": "unknown",
        "dataset": "unknown",
        "asset_class": "crypto",
        "market_type": "spot",
        "exchange": None,
        "available_from": "2020-01-01T00:00:00Z",
        "available_until": None,
        "resolution": "1m",
        "access_method": "official_rest_api",
        "license_type": "exchange_public_api_tos",
        "commercial_use_allowed": True,
        "redistribution_allowed": False,
        "training_allowed": True,
        "retention_allowed": True,
        "revision_policy": "exchange_may_correct",
        "point_in_time_capable": True,
        "rate_limit": "1200/min_weight",
        "cost_class": "free",
        "owner": "nexus_data_moat",
        "last_verified_at": "2026-08-06T00:00:00Z",
        "status": "APPROVED_PUBLIC",
        "adapter_contract_ok": True,
        "public_display_allowed": True,
        "authorization_claimed": False,
        "notes": "fixture",
    }
    base.update(overrides)
    return base


def fixture_sources() -> list[dict[str, Any]]:
    """Bounded fixture set covering each status class with legal access only."""
    return [
        _src(
            source_id="binance_spot_klines_1m",
            provider="binance",
            dataset="spot_klines",
            asset_class="crypto",
            market_type="spot",
            exchange="binance",
            available_from="2017-08-17T00:00:00Z",
            resolution="1m",
            access_method="official_rest_api",
            license_type="exchange_public_api_tos",
            commercial_use_allowed=True,
            redistribution_allowed=False,
            training_allowed=True,
            retention_allowed=True,
            revision_policy="exchange_may_correct",
            point_in_time_capable=True,
            rate_limit="1200/min_weight",
            cost_class="free",
            status="APPROVED_PUBLIC",
            public_display_allowed=True,
            authorization_claimed=False,
            notes="Official Binance REST klines; public market data.",
        ),
        _src(
            source_id="bybit_linear_klines_1m",
            provider="bybit",
            dataset="linear_klines",
            asset_class="crypto",
            market_type="perpetual",
            exchange="bybit",
            available_from="2018-01-01T00:00:00Z",
            resolution="1m",
            access_method="official_rest_api",
            license_type="exchange_public_api_tos",
            commercial_use_allowed=True,
            redistribution_allowed=False,
            training_allowed=True,
            retention_allowed=True,
            revision_policy="exchange_may_correct",
            point_in_time_capable=True,
            rate_limit="120/5s",
            cost_class="free",
            status="APPROVED_INTERNAL_ONLY",
            public_display_allowed=False,
            authorization_claimed=False,
            notes="Official Bybit linear klines; internal research use.",
        ),
        _src(
            source_id="bitcoin_core_blocks_self_hosted",
            provider="bitcoin_core",
            dataset="blocks",
            asset_class="crypto",
            market_type="onchain",
            exchange=None,
            available_from="2009-01-03T00:00:00Z",
            resolution="block",
            access_method="self_hosted_node",
            license_type="public_chain_data",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            training_allowed=True,
            retention_allowed=True,
            revision_policy="immutable_append",
            point_in_time_capable=True,
            rate_limit="local_disk_bound",
            cost_class="self_hosted",
            status="APPROVED_PUBLIC",
            public_display_allowed=True,
            authorization_claimed=False,
            notes="Self-hosted Bitcoin Core; public chain data.",
        ),
        _src(
            source_id="vendor_x_metrics_api_review",
            provider="vendor_x",
            dataset="onchain_metrics",
            asset_class="crypto",
            market_type="derived",
            exchange=None,
            available_from="2022-01-01T00:00:00Z",
            resolution="1h",
            access_method="founder_authorized_commercial_api",
            license_type="pending_legal_review",
            commercial_use_allowed=False,
            redistribution_allowed=False,
            training_allowed=False,
            retention_allowed=False,
            revision_policy="vendor_may_revise",
            point_in_time_capable=False,
            rate_limit="60/min",
            cost_class="paid",
            status="LICENSE_REVIEW_REQUIRED",
            adapter_contract_ok=True,
            public_display_allowed=False,
            authorization_claimed=False,
            notes=(
                "Adapter contract OK only. NO training, NO public display, "
                "NO claim of authorization until legal clears."
            ),
        ),
        _src(
            source_id="commercial_feed_no_redistribute",
            provider="authorized_feed_co",
            dataset="orderbook_l2_snapshot",
            asset_class="crypto",
            market_type="spot",
            exchange="multi",
            available_from="2021-06-01T00:00:00Z",
            resolution="100ms",
            access_method="founder_authorized_commercial_api",
            license_type="commercial_no_redistribute",
            commercial_use_allowed=True,
            redistribution_allowed=False,
            training_allowed=True,
            retention_allowed=True,
            revision_policy="vendor_may_revise",
            point_in_time_capable=True,
            rate_limit="contractual",
            cost_class="enterprise",
            status="REDISTRIBUTION_FORBIDDEN",
            public_display_allowed=False,
            authorization_claimed=True,
            notes="Founder-authorized commercial API; redistribution forbidden.",
        ),
        _src(
            source_id="research_corpus_no_training",
            provider="research_corp",
            dataset="labeled_events",
            asset_class="crypto",
            market_type="events",
            exchange=None,
            available_from="2019-01-01T00:00:00Z",
            resolution="event",
            access_method="commercial_ok_dataset",
            license_type="commercial_no_ml_training",
            commercial_use_allowed=True,
            redistribution_allowed=False,
            training_allowed=False,
            retention_allowed=True,
            revision_policy="vendor_may_revise",
            point_in_time_capable=True,
            rate_limit="bulk_download_daily",
            cost_class="paid",
            status="TRAINING_FORBIDDEN",
            public_display_allowed=False,
            authorization_claimed=True,
            notes="Commercial-ok dataset; ML training forbidden by license.",
        ),
        _src(
            source_id="legacy_ftx_spot_klines_1m",
            provider="ftx",
            dataset="spot_klines",
            asset_class="crypto",
            market_type="spot",
            exchange="ftx",
            available_from="2019-01-01T00:00:00Z",
            available_until="2022-11-11T00:00:00Z",
            resolution="1m",
            access_method="local_fixture",
            license_type="historical_archive_internal",
            commercial_use_allowed=False,
            redistribution_allowed=False,
            training_allowed=False,
            retention_allowed=True,
            revision_policy="immutable_append",
            point_in_time_capable=True,
            rate_limit="n/a",
            cost_class="free",
            status="DEPRECATED",
            public_display_allowed=False,
            authorization_claimed=False,
            notes="Deprecated exchange archive; fixture-only retention.",
        ),
        _src(
            source_id="okx_options_chain_unavailable",
            provider="okx",
            dataset="options_chain",
            asset_class="crypto",
            market_type="options",
            exchange="okx",
            available_from=None,
            available_until=None,
            resolution="snapshot",
            access_method="official_rest_api",
            license_type="exchange_public_api_tos",
            commercial_use_allowed=True,
            redistribution_allowed=False,
            training_allowed=False,
            retention_allowed=False,
            revision_policy="unknown",
            point_in_time_capable=False,
            rate_limit="unknown",
            cost_class="unknown",
            status="UNAVAILABLE",
            public_display_allowed=False,
            authorization_claimed=False,
            notes="Endpoint not wired; marked unavailable.",
        ),
    ]


def build_fixture_registry_document() -> dict[str, Any]:
    return {
        "schema": SCHEMA,
        "schema_version": SCHEMA_VERSION,
        "lane": LANE,
        "lane_name": "DATA_SOURCE_AND_LICENSE_REGISTRY",
        "hard_bans": [
            "no_glassnode_paywall_scrape",
            "no_coinglass_paywall_scrape",
            "no_messari_paywall_scrape",
            "no_auth_bypass",
            "no_rate_limit_bypass",
        ],
        "sources": fixture_sources(),
    }


def write_fixture_artifact(root: Path | None = None) -> Path:
    if root is None:
        root = Path(__file__).resolve().parents[2]
    path = root / FIXTURES_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(build_fixture_registry_document(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return path
