"""AI profile queue identities for Blind Reflection V2.3."""
from __future__ import annotations

GROQ_REFLECTION_REASONER = "GROQ_REFLECTION_REASONER"
SAMBANOVA_INDEPENDENT_CRITIC = "SAMBANOVA_INDEPENDENT_CRITIC"
CEREBRAS_RESEARCH_NORMALIZER = "CEREBRAS_RESEARCH_NORMALIZER"
GROQ_MAIN_REASONER = "GROQ_MAIN_REASONER"

PROVIDER_PROFILES = (
    GROQ_REFLECTION_REASONER,
    SAMBANOVA_INDEPENDENT_CRITIC,
    CEREBRAS_RESEARCH_NORMALIZER,
    GROQ_MAIN_REASONER,
)

# Default token-bucket params: burst / refill per second (conservative).
DEFAULT_BUCKET_PARAMS: dict[str, tuple[float, float]] = {
    GROQ_REFLECTION_REASONER: (5.0, 0.2),
    SAMBANOVA_INDEPENDENT_CRITIC: (3.0, 0.1),
    CEREBRAS_RESEARCH_NORMALIZER: (4.0, 0.15),
    GROQ_MAIN_REASONER: (4.0, 0.15),
}

MAX_PROVIDER_RETRIES = 5
